# -*- coding: utf-8 -*-
"""
module for making certain substitutions of unicode characters to ascii equivalents
"""

def normalize(string, sub_table=None):
    '''
    normalize a unicode string, replacing recognized chars with substitutions and
    leaving the rest untouched

    string -- unicode -- the input (must be unicode)
    sub_table -- dict -- {unicode: unicode} if you want to override or add to the default substitutions

    return -- unicode -- the string with substitutions if any were found
    '''
    if not isinstance(string, unicode):
        raise UnicodeError("expected string to be a unicode string")

    # with our substitution table powers combined, we have the power!!!!
    stable = {}
    if sub_table is not None:
        stable.update(substitution_table)
        stable.update(sub_table)
    else:
        stable = substitution_table

    chars = []
    for char in string:
        chars.append(stable[char] if (char in stable) else char)

    return u''.join(chars)

substitution_table = {
    u'\u0020': u' ', # SPACE
    u'\u0021': u'!', # EXCLAMATION MARK
    u'\u0022': u'"', # QUOTATION MARK
    u'\u0023': u'#', # NUMBER SIGN
    u'\u0024': u'$', # DOLLAR SIGN
    u'\u0025': u'%', # PERCENT SIGN
    u'\u0026': u'&', # AMPERSAND
    u'\u0027': u"'", # APOSTROPHE
    u'\u0028': u'(', # LEFT PARENTHESIS
    u'\u0029': u')', # RIGHT PARENTHESIS
    u'\u002A': u'*', # ASTERISK
    u'\u002B': u'+', # PLUS SIGN
    u'\u002C': u',', # COMMA
    u'\u002D': u'-', # HYPHEN-MINUS
    u'\u002E': u'.', # FULL STOP
    u'\u002F': u'/', # SOLIDUS
    u'\u0030': u'0', # DIGIT ZERO
    u'\u0031': u'1', # DIGIT ONE
    u'\u0032': u'2', # DIGIT TWO
    u'\u0033': u'3', # DIGIT THREE
    u'\u0034': u'4', # DIGIT FOUR
    u'\u0035': u'5', # DIGIT FIVE
    u'\u0036': u'6', # DIGIT SIX
    u'\u0037': u'7', # DIGIT SEVEN
    u'\u0038': u'8', # DIGIT EIGHT
    u'\u0039': u'9', # DIGIT NINE
    u'\u003A': u':', # COLON
    u'\u003B': u';', # SEMICOLON
    u'\u003C': u'<', # LESS-THAN SIGN
    u'\u003D': u'=', # EQUALS SIGN
    u'\u003E': u'>', # GREATER-THAN SIGN
    u'\u003F': u'?', # QUESTION MARK
    u'\u0040': u'@', # COMMERCIAL AT
    u'\u0041': u'A', # LATIN CAPITAL LETTER A
    u'\u0042': u'B', # LATIN CAPITAL LETTER B
    u'\u0043': u'C', # LATIN CAPITAL LETTER C
    u'\u0044': u'D', # LATIN CAPITAL LETTER D
    u'\u0045': u'E', # LATIN CAPITAL LETTER E
    u'\u0046': u'F', # LATIN CAPITAL LETTER F
    u'\u0047': u'G', # LATIN CAPITAL LETTER G
    u'\u0048': u'H', # LATIN CAPITAL LETTER H
    u'\u0049': u'I', # LATIN CAPITAL LETTER I
    u'\u004A': u'J', # LATIN CAPITAL LETTER J
    u'\u004B': u'K', # LATIN CAPITAL LETTER K
    u'\u004C': u'L', # LATIN CAPITAL LETTER L
    u'\u004D': u'M', # LATIN CAPITAL LETTER M
    u'\u004E': u'N', # LATIN CAPITAL LETTER N
    u'\u004F': u'O', # LATIN CAPITAL LETTER O
    u'\u0050': u'P', # LATIN CAPITAL LETTER P
    u'\u0051': u'Q', # LATIN CAPITAL LETTER Q
    u'\u0052': u'R', # LATIN CAPITAL LETTER R
    u'\u0053': u'S', # LATIN CAPITAL LETTER S
    u'\u0054': u'T', # LATIN CAPITAL LETTER T
    u'\u0055': u'U', # LATIN CAPITAL LETTER U
    u'\u0056': u'V', # LATIN CAPITAL LETTER V
    u'\u0057': u'W', # LATIN CAPITAL LETTER W
    u'\u0058': u'X', # LATIN CAPITAL LETTER X
    u'\u0059': u'Y', # LATIN CAPITAL LETTER Y
    u'\u005A': u'Z', # LATIN CAPITAL LETTER Z
    u'\u005B': u'[', # LEFT SQUARE BRACKET
    u'\u005C': u'\\', # REVERSE SOLIDUS
    u'\u005D': u']', # RIGHT SQUARE BRACKET
    u'\u005E': u'^', # CIRCUMFLEX ACCENT
    u'\u005F': u'_', # LOW LINE
    u'\u0060': u'`', # GRAVE ACCENT
    u'\u0061': u'a', # LATIN SMALL LETTER A
    u'\u0062': u'b', # LATIN SMALL LETTER B
    u'\u0063': u'c', # LATIN SMALL LETTER C
    u'\u0064': u'd', # LATIN SMALL LETTER D
    u'\u0065': u'e', # LATIN SMALL LETTER E
    u'\u0066': u'f', # LATIN SMALL LETTER F
    u'\u0067': u'g', # LATIN SMALL LETTER G
    u'\u0068': u'h', # LATIN SMALL LETTER H
    u'\u0069': u'i', # LATIN SMALL LETTER I
    u'\u006A': u'j', # LATIN SMALL LETTER J
    u'\u006B': u'k', # LATIN SMALL LETTER K
    u'\u006C': u'l', # LATIN SMALL LETTER L
    u'\u006D': u'm', # LATIN SMALL LETTER M
    u'\u006E': u'n', # LATIN SMALL LETTER N
    u'\u006F': u'o', # LATIN SMALL LETTER O
    u'\u0070': u'p', # LATIN SMALL LETTER P
    u'\u0071': u'q', # LATIN SMALL LETTER Q
    u'\u0072': u'r', # LATIN SMALL LETTER R
    u'\u0073': u's', # LATIN SMALL LETTER S
    u'\u0074': u't', # LATIN SMALL LETTER T
    u'\u0075': u'u', # LATIN SMALL LETTER U
    u'\u0076': u'v', # LATIN SMALL LETTER V
    u'\u0077': u'w', # LATIN SMALL LETTER W
    u'\u0078': u'x', # LATIN SMALL LETTER X
    u'\u0079': u'y', # LATIN SMALL LETTER Y
    u'\u007A': u'z', # LATIN SMALL LETTER Z
    u'\u007B': u'{', # LEFT CURLY BRACKET
    u'\u007C': u'', # VERTICAL LINE
    u'\u007D': u'}', # RIGHT CURLY BRACKET
    u'\u007E': u'~', # TILDE
    u'\u00A0': u' ', # NO-BREAK SPACE
    u'\u00A6': u'', # BROKEN BAR
    u'\u00A9': u'(c)', # COPYRIGHT SIGN
    u'\u00AA': u'a', # FEMININE ORDINAL INDICATOR
    u'\u00AB': u'"', # LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
    u'\u00AD': u'-', # SOFT HYPHEN
    u'\u00AE': u'(r)', # REGISTERED SIGN
    u'\u00B1': u'+/-', # PLUS-MINUS SIGN
    u'\u00B2': u'2', # SUPERSCRIPT TWO
    u'\u00B3': u'3', # SUPERSCRIPT THREE
    u'\u00B4': u"'", # ACUTE ACCENT
    u'\u00B5': u'u', # MICRO SIGN
    u'\u00B9': u'1', # SUPERSCRIPT ONE
    u'\u00BA': u'o', # MASCULINE ORDINAL INDICATOR
    u'\u00BB': u'"', # RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
    u'\u00BC': u'1/4', # VULGAR FRACTION ONE QUARTER
    u'\u00BD': u'1/2', # VULGAR FRACTION ONE HALF
    u'\u00BE': u'3/4', # VULGAR FRACTION THREE QUARTERS
    u'\u00C0': u'A', # LATIN CAPITAL LETTER A WITH GRAVE
    u'\u00C1': u'A', # LATIN CAPITAL LETTER A WITH ACUTE
    u'\u00C2': u'A', # LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    u'\u00C3': u'A', # LATIN CAPITAL LETTER A WITH TILDE
    u'\u00C4': u'A', # LATIN CAPITAL LETTER A WITH DIAERESIS
    u'\u00C5': u'A', # LATIN CAPITAL LETTER A WITH RING ABOVE
    u'\u00C6': u'AE', # LATIN CAPITAL LETTER AE
    u'\u00C7': u'C', # LATIN CAPITAL LETTER C WITH CEDILLA
    u'\u00C8': u'E', # LATIN CAPITAL LETTER E WITH GRAVE
    u'\u00C9': u'E', # LATIN CAPITAL LETTER E WITH ACUTE
    u'\u00CA': u'E', # LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    u'\u00CB': u'E', # LATIN CAPITAL LETTER E WITH DIAERESIS
    u'\u00CC': u'I', # LATIN CAPITAL LETTER I WITH GRAVE
    u'\u00CD': u'I', # LATIN CAPITAL LETTER I WITH ACUTE
    u'\u00CE': u'I', # LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    u'\u00CF': u'I', # LATIN CAPITAL LETTER I WITH DIAERESIS
    u'\u00D1': u'N', # LATIN CAPITAL LETTER N WITH TILDE
    u'\u00D2': u'O', # LATIN CAPITAL LETTER O WITH GRAVE
    u'\u00D3': u'O', # LATIN CAPITAL LETTER O WITH ACUTE
    u'\u00D4': u'O', # LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    u'\u00D5': u'O', # LATIN CAPITAL LETTER O WITH TILDE
    u'\u00D6': u'O', # LATIN CAPITAL LETTER O WITH DIAERESIS
    u'\u00D7': u'*', # MULTIPLICATION SIGN
    u'\u00D8': u'O', # LATIN CAPITAL LETTER O WITH STROKE
    u'\u00D9': u'U', # LATIN CAPITAL LETTER U WITH GRAVE
    u'\u00DA': u'U', # LATIN CAPITAL LETTER U WITH ACUTE
    u'\u00DB': u'U', # LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    u'\u00DC': u'U', # LATIN CAPITAL LETTER U WITH DIAERESIS
    u'\u00DD': u'Y', # LATIN CAPITAL LETTER Y WITH ACUTE
    u'\u00DF': u'beta', # LATIN SMALL LETTER SHARP S
    u'\u00E0': u'a', # LATIN SMALL LETTER A WITH GRAVE
    u'\u00E1': u'a', # LATIN SMALL LETTER A WITH ACUTE
    u'\u00E2': u'a', # LATIN SMALL LETTER A WITH CIRCUMFLEX
    u'\u00E3': u'a', # LATIN SMALL LETTER A WITH TILDE
    u'\u00E4': u'a', # LATIN SMALL LETTER A WITH DIAERESIS
    u'\u00E5': u'a', # LATIN SMALL LETTER A WITH RING ABOVE
    u'\u00E6': u'ae', # LATIN SMALL LETTER AE
    u'\u00E7': u'c', # LATIN SMALL LETTER C WITH CEDILLA
    u'\u00E8': u'e', # LATIN SMALL LETTER E WITH GRAVE
    u'\u00E9': u'e', # LATIN SMALL LETTER E WITH ACUTE
    u'\u00EA': u'e', # LATIN SMALL LETTER E WITH CIRCUMFLEX
    u'\u00EB': u'e', # LATIN SMALL LETTER E WITH DIAERESIS
    u'\u00EC': u'i', # LATIN SMALL LETTER I WITH GRAVE
    u'\u00ED': u'i', # LATIN SMALL LETTER I WITH ACUTE
    u'\u00EE': u'i', # LATIN SMALL LETTER I WITH CIRCUMFLEX
    u'\u00EF': u'i', # LATIN SMALL LETTER I WITH DIAERESIS
    u'\u00F1': u'n', # LATIN SMALL LETTER N WITH TILDE
    u'\u00F2': u'o', # LATIN SMALL LETTER O WITH GRAVE
    u'\u00F3': u'o', # LATIN SMALL LETTER O WITH ACUTE
    u'\u00F4': u'o', # LATIN SMALL LETTER O WITH CIRCUMFLEX
    u'\u00F5': u'o', # LATIN SMALL LETTER O WITH TILDE
    u'\u00F6': u'o', # LATIN SMALL LETTER O WITH DIAERESIS
    u'\u00F7': u'/', # DIVISION SIGN
    u'\u00F8': u'o', # LATIN SMALL LETTER O WITH STROKE
    u'\u00F9': u'u', # LATIN SMALL LETTER U WITH GRAVE
    u'\u00FA': u'u', # LATIN SMALL LETTER U WITH ACUTE
    u'\u00FB': u'u', # LATIN SMALL LETTER U WITH CIRCUMFLEX
    u'\u00FC': u'u', # LATIN SMALL LETTER U WITH DIAERESIS
    u'\u00FD': u'y', # LATIN SMALL LETTER Y WITH ACUTE
    u'\u00FF': u'y', # LATIN SMALL LETTER Y WITH DIAERESIS
    u'\u0100': u'A', # LATIN CAPITAL LETTER A WITH MACRON
    u'\u0101': u'a', # LATIN SMALL LETTER A WITH MACRON
    u'\u0102': u'A', # LATIN CAPITAL LETTER A WITH BREVE
    u'\u0103': u'a', # LATIN SMALL LETTER A WITH BREVE
    u'\u0104': u'A', # LATIN CAPITAL LETTER A WITH OGONEK
    u'\u0105': u'a', # LATIN SMALL LETTER A WITH OGONEK
    u'\u0106': u'C', # LATIN CAPITAL LETTER C WITH ACUTE
    u'\u0107': u'c', # LATIN SMALL LETTER C WITH ACUTE
    u'\u0108': u'C', # LATIN CAPITAL LETTER C WITH CIRCUMFLEX
    u'\u0109': u'c', # LATIN SMALL LETTER C WITH CIRCUMFLEX
    u'\u010A': u'C', # LATIN CAPITAL LETTER C WITH DOT ABOVE
    u'\u010B': u'c', # LATIN SMALL LETTER C WITH DOT ABOVE
    u'\u010C': u'C', # LATIN CAPITAL LETTER C WITH CARON
    u'\u010D': u'c', # LATIN SMALL LETTER C WITH CARON
    u'\u010E': u'D', # LATIN CAPITAL LETTER D WITH CARON
    u'\u010F': u'd', # LATIN SMALL LETTER D WITH CARON
    u'\u0110': u'D', # LATIN CAPITAL LETTER D WITH STROKE
    u'\u0111': u'd', # LATIN SMALL LETTER D WITH STROKE
    u'\u0112': u'E', # LATIN CAPITAL LETTER E WITH MACRON
    u'\u0113': u'e', # LATIN SMALL LETTER E WITH MACRON
    u'\u0114': u'E', # LATIN CAPITAL LETTER E WITH BREVE
    u'\u0115': u'e', # LATIN SMALL LETTER E WITH BREVE
    u'\u0116': u'E', # LATIN CAPITAL LETTER E WITH DOT ABOVE
    u'\u0117': u'e', # LATIN SMALL LETTER E WITH DOT ABOVE
    u'\u0118': u'E', # LATIN CAPITAL LETTER E WITH OGONEK
    u'\u0119': u'e', # LATIN SMALL LETTER E WITH OGONEK
    u'\u011A': u'E', # LATIN CAPITAL LETTER E WITH CARON
    u'\u011B': u'e', # LATIN SMALL LETTER E WITH CARON
    u'\u011C': u'G', # LATIN CAPITAL LETTER G WITH CIRCUMFLEX
    u'\u011D': u'g', # LATIN SMALL LETTER G WITH CIRCUMFLEX
    u'\u011E': u'G', # LATIN CAPITAL LETTER G WITH BREVE
    u'\u011F': u'g', # LATIN SMALL LETTER G WITH BREVE
    u'\u0120': u'G', # LATIN CAPITAL LETTER G WITH DOT ABOVE
    u'\u0121': u'g', # LATIN SMALL LETTER G WITH DOT ABOVE
    u'\u0122': u'G', # LATIN CAPITAL LETTER G WITH CEDILLA
    u'\u0123': u'g', # LATIN SMALL LETTER G WITH CEDILLA
    u'\u0124': u'H', # LATIN CAPITAL LETTER H WITH CIRCUMFLEX
    u'\u0125': u'h', # LATIN SMALL LETTER H WITH CIRCUMFLEX
    u'\u0126': u'H', # LATIN CAPITAL LETTER H WITH STROKE
    u'\u0127': u'h', # LATIN SMALL LETTER H WITH STROKE
    u'\u0128': u'I', # LATIN CAPITAL LETTER I WITH TILDE
    u'\u0129': u'i', # LATIN SMALL LETTER I WITH TILDE
    u'\u012A': u'I', # LATIN CAPITAL LETTER I WITH MACRON
    u'\u012B': u'i', # LATIN SMALL LETTER I WITH MACRON
    u'\u012C': u'I', # LATIN CAPITAL LETTER I WITH BREVE
    u'\u012D': u'i', # LATIN SMALL LETTER I WITH BREVE
    u'\u012E': u'I', # LATIN CAPITAL LETTER I WITH OGONEK
    u'\u012F': u'i', # LATIN SMALL LETTER I WITH OGONEK
    u'\u0130': u'I', # LATIN CAPITAL LETTER I WITH DOT ABOVE
    u'\u0131': u'i', # LATIN SMALL LETTER DOTLESS I
    u'\u0132': u'IJ', # LATIN CAPITAL LIGATURE IJ
    u'\u0133': u'ij', # LATIN SMALL LIGATURE IJ
    u'\u0134': u'J', # LATIN CAPITAL LETTER J WITH CIRCUMFLEX
    u'\u0135': u'j', # LATIN SMALL LETTER J WITH CIRCUMFLEX
    u'\u0136': u'K', # LATIN CAPITAL LETTER K WITH CEDILLA
    u'\u0137': u'k', # LATIN SMALL LETTER K WITH CEDILLA
    u'\u0139': u'L', # LATIN CAPITAL LETTER L WITH ACUTE
    u'\u013A': u'l', # LATIN SMALL LETTER L WITH ACUTE
    u'\u013B': u'L', # LATIN CAPITAL LETTER L WITH CEDILLA
    u'\u013C': u'l', # LATIN SMALL LETTER L WITH CEDILLA
    u'\u013D': u'L', # LATIN CAPITAL LETTER L WITH CARON
    u'\u013E': u'l', # LATIN SMALL LETTER L WITH CARON
    u'\u013F': u'L', # LATIN CAPITAL LETTER L WITH MIDDLE DOT
    u'\u0140': u'l', # LATIN SMALL LETTER L WITH MIDDLE DOT
    u'\u0141': u'L', # LATIN CAPITAL LETTER L WITH STROKE
    u'\u0142': u'l', # LATIN SMALL LETTER L WITH STROKE
    u'\u0143': u'N', # LATIN CAPITAL LETTER N WITH ACUTE
    u'\u0144': u'n', # LATIN SMALL LETTER N WITH ACUTE
    u'\u0145': u'N', # LATIN CAPITAL LETTER N WITH CEDILLA
    u'\u0146': u'n', # LATIN SMALL LETTER N WITH CEDILLA
    u'\u0147': u'N', # LATIN CAPITAL LETTER N WITH CARON
    u'\u0148': u'n', # LATIN SMALL LETTER N WITH CARON
    u'\u0149': u'n', # LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
    u'\u014C': u'O', # LATIN CAPITAL LETTER O WITH MACRON
    u'\u014D': u'o', # LATIN SMALL LETTER O WITH MACRON
    u'\u014E': u'O', # LATIN CAPITAL LETTER O WITH BREVE
    u'\u014F': u'o', # LATIN SMALL LETTER O WITH BREVE
    u'\u0150': u'O', # LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    u'\u0151': u'o', # LATIN SMALL LETTER O WITH DOUBLE ACUTE
    u'\u0152': u'OE', # LATIN CAPITAL LIGATURE OE
    u'\u0153': u'oe', # LATIN SMALL LIGATURE OE
    u'\u0154': u'R', # LATIN CAPITAL LETTER R WITH ACUTE
    u'\u0155': u'r', # LATIN SMALL LETTER R WITH ACUTE
    u'\u0156': u'R', # LATIN CAPITAL LETTER R WITH CEDILLA
    u'\u0157': u'r', # LATIN SMALL LETTER R WITH CEDILLA
    u'\u0158': u'R', # LATIN CAPITAL LETTER R WITH CARON
    u'\u0159': u'r', # LATIN SMALL LETTER R WITH CARON
    u'\u015A': u'S', # LATIN CAPITAL LETTER S WITH ACUTE
    u'\u015B': u's', # LATIN SMALL LETTER S WITH ACUTE
    u'\u015C': u'S', # LATIN CAPITAL LETTER S WITH CIRCUMFLEX
    u'\u015D': u's', # LATIN SMALL LETTER S WITH CIRCUMFLEX
    u'\u015E': u'S', # LATIN CAPITAL LETTER S WITH CEDILLA
    u'\u015F': u's', # LATIN SMALL LETTER S WITH CEDILLA
    u'\u0160': u'S', # LATIN CAPITAL LETTER S WITH CARON
    u'\u0161': u's', # LATIN SMALL LETTER S WITH CARON
    u'\u0162': u'T', # LATIN CAPITAL LETTER T WITH CEDILLA
    u'\u0163': u't', # LATIN SMALL LETTER T WITH CEDILLA
    u'\u0164': u'T', # LATIN CAPITAL LETTER T WITH CARON
    u'\u0165': u't', # LATIN SMALL LETTER T WITH CARON
    u'\u0166': u'T', # LATIN CAPITAL LETTER T WITH STROKE
    u'\u0167': u't', # LATIN SMALL LETTER T WITH STROKE
    u'\u0168': u'U', # LATIN CAPITAL LETTER U WITH TILDE
    u'\u0169': u'u', # LATIN SMALL LETTER U WITH TILDE
    u'\u016A': u'U', # LATIN CAPITAL LETTER U WITH MACRON
    u'\u016B': u'u', # LATIN SMALL LETTER U WITH MACRON
    u'\u016C': u'U', # LATIN CAPITAL LETTER U WITH BREVE
    u'\u016D': u'u', # LATIN SMALL LETTER U WITH BREVE
    u'\u016E': u'U', # LATIN CAPITAL LETTER U WITH RING ABOVE
    u'\u016F': u'u', # LATIN SMALL LETTER U WITH RING ABOVE
    u'\u0170': u'U', # LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    u'\u0171': u'u', # LATIN SMALL LETTER U WITH DOUBLE ACUTE
    u'\u0172': u'U', # LATIN CAPITAL LETTER U WITH OGONEK
    u'\u0173': u'u', # LATIN SMALL LETTER U WITH OGONEK
    u'\u0174': u'W', # LATIN CAPITAL LETTER W WITH CIRCUMFLEX
    u'\u0175': u'w', # LATIN SMALL LETTER W WITH CIRCUMFLEX
    u'\u0176': u'Y', # LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
    u'\u0177': u'y', # LATIN SMALL LETTER Y WITH CIRCUMFLEX
    u'\u0178': u'Y', # LATIN CAPITAL LETTER Y WITH DIAERESIS
    u'\u0179': u'Z', # LATIN CAPITAL LETTER Z WITH ACUTE
    u'\u017A': u'z', # LATIN SMALL LETTER Z WITH ACUTE
    u'\u017B': u'Z', # LATIN CAPITAL LETTER Z WITH DOT ABOVE
    u'\u017C': u'z', # LATIN SMALL LETTER Z WITH DOT ABOVE
    u'\u017D': u'Z', # LATIN CAPITAL LETTER Z WITH CARON
    u'\u017E': u'z', # LATIN SMALL LETTER Z WITH CARON
    u'\u017F': u's', # LATIN SMALL LETTER LONG S
    u'\u0180': u'b', # LATIN SMALL LETTER B WITH STROKE
    u'\u0181': u'B', # LATIN CAPITAL LETTER B WITH HOOK
    u'\u0182': u'B', # LATIN CAPITAL LETTER B WITH TOPBAR
    u'\u0183': u'b', # LATIN SMALL LETTER B WITH TOPBAR
    u'\u0184': u'6', # LATIN CAPITAL LETTER TONE SIX
    u'\u0185': u'6', # LATIN SMALL LETTER TONE SIX
    u'\u0186': u'O', # LATIN CAPITAL LETTER OPEN O
    u'\u0187': u'C', # LATIN CAPITAL LETTER C WITH HOOK
    u'\u0188': u'c', # LATIN SMALL LETTER C WITH HOOK
    u'\u0189': u'D', # LATIN CAPITAL LETTER AFRICAN D
    u'\u018A': u'D', # LATIN CAPITAL LETTER D WITH HOOK
    u'\u018B': u'D', # LATIN CAPITAL LETTER D WITH TOPBAR
    u'\u018C': u'd', # LATIN SMALL LETTER D WITH TOPBAR
    u'\u018E': u'E', # LATIN CAPITAL LETTER REVERSED E
    u'\u0190': u'E', # LATIN CAPITAL LETTER OPEN E
    u'\u0191': u'F', # LATIN CAPITAL LETTER F WITH HOOK
    u'\u0192': u'f', # LATIN SMALL LETTER F WITH HOOK
    u'\u0193': u'G', # LATIN CAPITAL LETTER G WITH HOOK
    u'\u0194': u'Gamma', # LATIN CAPITAL LETTER GAMMA
    u'\u0195': u'hv', # LATIN SMALL LETTER HV
    u'\u0196': u'Iota', # LATIN CAPITAL LETTER IOTA
    u'\u0197': u'I', # LATIN CAPITAL LETTER I WITH STROKE
    u'\u0198': u'K', # LATIN CAPITAL LETTER K WITH HOOK
    u'\u0199': u'k', # LATIN SMALL LETTER K WITH HOOK
    u'\u019A': u'l', # LATIN SMALL LETTER L WITH BAR
    u'\u019B': u'lambda', # LATIN SMALL LETTER LAMBDA WITH STROKE
    u'\u019C': u'M', # LATIN CAPITAL LETTER TURNED M
    u'\u019D': u'N', # LATIN CAPITAL LETTER N WITH LEFT HOOK
    u'\u019E': u'n', # LATIN SMALL LETTER N WITH LONG RIGHT LEG
    u'\u019F': u'O', # LATIN CAPITAL LETTER O WITH MIDDLE TILDE
    u'\u01A0': u'O', # LATIN CAPITAL LETTER O WITH HORN
    u'\u01A1': u'o', # LATIN SMALL LETTER O WITH HORN
    u'\u01A2': u'OI', # LATIN CAPITAL LETTER OI
    u'\u01A3': u'oi', # LATIN SMALL LETTER OI
    u'\u01A4': u'P', # LATIN CAPITAL LETTER P WITH HOOK
    u'\u01A5': u'p', # LATIN SMALL LETTER P WITH HOOK
    u'\u01A6': u'YR', # LATIN LETTER YR
    u'\u01A7': u'2', # LATIN CAPITAL LETTER TONE TWO
    u'\u01A8': u'2', # LATIN SMALL LETTER TONE TWO
    u'\u01AB': u't', # LATIN SMALL LETTER T WITH PALATAL HOOK
    u'\u01AC': u'T', # LATIN CAPITAL LETTER T WITH HOOK
    u'\u01AD': u't', # LATIN SMALL LETTER T WITH HOOK
    u'\u01AE': u'T', # LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
    u'\u01AF': u'U', # LATIN CAPITAL LETTER U WITH HORN
    u'\u01B0': u'u', # LATIN SMALL LETTER U WITH HORN
    u'\u01B1': u'Upsilon', # LATIN CAPITAL LETTER UPSILON
    u'\u01B2': u'V', # LATIN CAPITAL LETTER V WITH HOOK
    u'\u01B3': u'Y', # LATIN CAPITAL LETTER Y WITH HOOK
    u'\u01B4': u'y', # LATIN SMALL LETTER Y WITH HOOK
    u'\u01B5': u'Z', # LATIN CAPITAL LETTER Z WITH STROKE
    u'\u01B6': u'z', # LATIN SMALL LETTER Z WITH STROKE
    u'\u01BB': u'2', # LATIN LETTER TWO WITH STROKE
    u'\u01BC': u'5', # LATIN CAPITAL LETTER TONE FIVE
    u'\u01BD': u'5', # LATIN SMALL LETTER TONE FIVE
    u'\u01C0': u'', # LATIN LETTER DENTAL CLICK
    u'\u01C3': u'!', # LATIN LETTER RETROFLEX CLICK
    u'\u01C4': u'DZ', # LATIN CAPITAL LETTER DZ WITH CARON
    u'\u01C5': u'Dz', # LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
    u'\u01C6': u'dz', # LATIN SMALL LETTER DZ WITH CARON
    u'\u01C7': u'LJ', # LATIN CAPITAL LETTER LJ
    u'\u01C8': u'Lj', # LATIN CAPITAL LETTER L WITH SMALL LETTER J
    u'\u01C9': u'lj', # LATIN SMALL LETTER LJ
    u'\u01CA': u'NJ', # LATIN CAPITAL LETTER NJ
    u'\u01CB': u'Nj', # LATIN CAPITAL LETTER N WITH SMALL LETTER J
    u'\u01CC': u'nj', # LATIN SMALL LETTER NJ
    u'\u01CD': u'A', # LATIN CAPITAL LETTER A WITH CARON
    u'\u01CE': u'a', # LATIN SMALL LETTER A WITH CARON
    u'\u01CF': u'I', # LATIN CAPITAL LETTER I WITH CARON
    u'\u01D0': u'i', # LATIN SMALL LETTER I WITH CARON
    u'\u01D1': u'O', # LATIN CAPITAL LETTER O WITH CARON
    u'\u01D2': u'o', # LATIN SMALL LETTER O WITH CARON
    u'\u01D3': u'U', # LATIN CAPITAL LETTER U WITH CARON
    u'\u01D4': u'u', # LATIN SMALL LETTER U WITH CARON
    u'\u01D5': u'U', # LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
    u'\u01D6': u'u', # LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
    u'\u01D7': u'U', # LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
    u'\u01D8': u'u', # LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
    u'\u01D9': u'U', # LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
    u'\u01DA': u'u', # LATIN SMALL LETTER U WITH DIAERESIS AND CARON
    u'\u01DB': u'U', # LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
    u'\u01DC': u'u', # LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
    u'\u01DD': u'e', # LATIN SMALL LETTER TURNED E
    u'\u01DE': u'A', # LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
    u'\u01DF': u'a', # LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
    u'\u01E0': u'A', # LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
    u'\u01E1': u'a', # LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
    u'\u01E2': u'AE', # LATIN CAPITAL LETTER AE WITH MACRON
    u'\u01E3': u'ae', # LATIN SMALL LETTER AE WITH MACRON
    u'\u01E4': u'G', # LATIN CAPITAL LETTER G WITH STROKE
    u'\u01E5': u'g', # LATIN SMALL LETTER G WITH STROKE
    u'\u01E6': u'G', # LATIN CAPITAL LETTER G WITH CARON
    u'\u01E7': u'g', # LATIN SMALL LETTER G WITH CARON
    u'\u01E8': u'K', # LATIN CAPITAL LETTER K WITH CARON
    u'\u01E9': u'k', # LATIN SMALL LETTER K WITH CARON
    u'\u01EA': u'O', # LATIN CAPITAL LETTER O WITH OGONEK
    u'\u01EB': u'o', # LATIN SMALL LETTER O WITH OGONEK
    u'\u01EC': u'O', # LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
    u'\u01ED': u'o', # LATIN SMALL LETTER O WITH OGONEK AND MACRON
    u'\u01F0': u'j', # LATIN SMALL LETTER J WITH CARON
    u'\u01F1': u'DZ', # LATIN CAPITAL LETTER DZ
    u'\u01F2': u'Dz', # LATIN CAPITAL LETTER D WITH SMALL LETTER Z
    u'\u01F3': u'dz', # LATIN SMALL LETTER DZ
    u'\u01F4': u'G', # LATIN CAPITAL LETTER G WITH ACUTE
    u'\u01F5': u'g', # LATIN SMALL LETTER G WITH ACUTE
    u'\u01F8': u'N', # LATIN CAPITAL LETTER N WITH GRAVE
    u'\u01F9': u'n', # LATIN SMALL LETTER N WITH GRAVE
    u'\u01FA': u'A', # LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
    u'\u01FB': u'a', # LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
    u'\u01FC': u'AE', # LATIN CAPITAL LETTER AE WITH ACUTE
    u'\u01FD': u'ae', # LATIN SMALL LETTER AE WITH ACUTE
    u'\u01FE': u'O', # LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
    u'\u01FF': u'o', # LATIN SMALL LETTER O WITH STROKE AND ACUTE
    u'\u0200': u'A', # LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
    u'\u0201': u'a', # LATIN SMALL LETTER A WITH DOUBLE GRAVE
    u'\u0202': u'A', # LATIN CAPITAL LETTER A WITH INVERTED BREVE
    u'\u0203': u'a', # LATIN SMALL LETTER A WITH INVERTED BREVE
    u'\u0204': u'E', # LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
    u'\u0205': u'e', # LATIN SMALL LETTER E WITH DOUBLE GRAVE
    u'\u0206': u'E', # LATIN CAPITAL LETTER E WITH INVERTED BREVE
    u'\u0207': u'e', # LATIN SMALL LETTER E WITH INVERTED BREVE
    u'\u0208': u'I', # LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
    u'\u0209': u'i', # LATIN SMALL LETTER I WITH DOUBLE GRAVE
    u'\u020A': u'I', # LATIN CAPITAL LETTER I WITH INVERTED BREVE
    u'\u020B': u'i', # LATIN SMALL LETTER I WITH INVERTED BREVE
    u'\u020C': u'O', # LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
    u'\u020D': u'o', # LATIN SMALL LETTER O WITH DOUBLE GRAVE
    u'\u020E': u'O', # LATIN CAPITAL LETTER O WITH INVERTED BREVE
    u'\u020F': u'o', # LATIN SMALL LETTER O WITH INVERTED BREVE
    u'\u0210': u'R', # LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
    u'\u0211': u'r', # LATIN SMALL LETTER R WITH DOUBLE GRAVE
    u'\u0212': u'R', # LATIN CAPITAL LETTER R WITH INVERTED BREVE
    u'\u0213': u'r', # LATIN SMALL LETTER R WITH INVERTED BREVE
    u'\u0214': u'U', # LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
    u'\u0215': u'u', # LATIN SMALL LETTER U WITH DOUBLE GRAVE
    u'\u0216': u'U', # LATIN CAPITAL LETTER U WITH INVERTED BREVE
    u'\u0217': u'u', # LATIN SMALL LETTER U WITH INVERTED BREVE
    u'\u0218': u'S', # LATIN CAPITAL LETTER S WITH COMMA BELOW
    u'\u0219': u's', # LATIN SMALL LETTER S WITH COMMA BELOW
    u'\u021A': u'T', # LATIN CAPITAL LETTER T WITH COMMA BELOW
    u'\u021B': u't', # LATIN SMALL LETTER T WITH COMMA BELOW
    u'\u021E': u'H', # LATIN CAPITAL LETTER H WITH CARON
    u'\u021F': u'h', # LATIN SMALL LETTER H WITH CARON
    u'\u0220': u'N', # LATIN CAPITAL LETTER N WITH LONG RIGHT LEG
    u'\u0221': u'd', # LATIN SMALL LETTER D WITH CURL
    u'\u0222': u'OU', # LATIN CAPITAL LETTER OU
    u'\u0223': u'ou', # LATIN SMALL LETTER OU
    u'\u0224': u'Z', # LATIN CAPITAL LETTER Z WITH HOOK
    u'\u0225': u'z', # LATIN SMALL LETTER Z WITH HOOK
    u'\u0226': u'A', # LATIN CAPITAL LETTER A WITH DOT ABOVE
    u'\u0227': u'a', # LATIN SMALL LETTER A WITH DOT ABOVE
    u'\u0228': u'E', # LATIN CAPITAL LETTER E WITH CEDILLA
    u'\u0229': u'e', # LATIN SMALL LETTER E WITH CEDILLA
    u'\u022A': u'O', # LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
    u'\u022B': u'o', # LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
    u'\u022C': u'O', # LATIN CAPITAL LETTER O WITH TILDE AND MACRON
    u'\u022D': u'o', # LATIN SMALL LETTER O WITH TILDE AND MACRON
    u'\u022E': u'O', # LATIN CAPITAL LETTER O WITH DOT ABOVE
    u'\u022F': u'o', # LATIN SMALL LETTER O WITH DOT ABOVE
    u'\u0230': u'O', # LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
    u'\u0231': u'o', # LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
    u'\u0232': u'Y', # LATIN CAPITAL LETTER Y WITH MACRON
    u'\u0233': u'y', # LATIN SMALL LETTER Y WITH MACRON
    u'\u0234': u'l', # LATIN SMALL LETTER L WITH CURL
    u'\u0235': u'n', # LATIN SMALL LETTER N WITH CURL
    u'\u0236': u't', # LATIN SMALL LETTER T WITH CURL
    u'\u0237': u'j', # LATIN SMALL LETTER DOTLESS J
    u'\u0238': u'db', # LATIN SMALL LETTER DB DIGRAPH
    u'\u0239': u'qp', # LATIN SMALL LETTER QP DIGRAPH
    u'\u023A': u'A', # LATIN CAPITAL LETTER A WITH STROKE
    u'\u023B': u'C', # LATIN CAPITAL LETTER C WITH STROKE
    u'\u023C': u'c', # LATIN SMALL LETTER C WITH STROKE
    u'\u023D': u'L', # LATIN CAPITAL LETTER L WITH BAR
    u'\u023E': u'T', # LATIN CAPITAL LETTER T WITH DIAGONAL STROKE
    u'\u023F': u's', # LATIN SMALL LETTER S WITH SWASH TAIL
    u'\u0240': u'z', # LATIN SMALL LETTER Z WITH SWASH TAIL
    u'\u0243': u'B', # LATIN CAPITAL LETTER B WITH STROKE
    u'\u0244': u'U', # LATIN CAPITAL LETTER U BAR
    u'\u0245': u'V', # LATIN CAPITAL LETTER TURNED V
    u'\u0246': u'E', # LATIN CAPITAL LETTER E WITH STROKE
    u'\u0247': u'e', # LATIN SMALL LETTER E WITH STROKE
    u'\u0248': u'J', # LATIN CAPITAL LETTER J WITH STROKE
    u'\u0249': u'j', # LATIN SMALL LETTER J WITH STROKE
    u'\u024A': u'Q', # LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL
    u'\u024B': u'q', # LATIN SMALL LETTER Q WITH HOOK TAIL
    u'\u024C': u'R', # LATIN CAPITAL LETTER R WITH STROKE
    u'\u024D': u'r', # LATIN SMALL LETTER R WITH STROKE
    u'\u024E': u'Y', # LATIN CAPITAL LETTER Y WITH STROKE
    u'\u024F': u'y', # LATIN SMALL LETTER Y WITH STROKE
    u'\u0250': u'a', # LATIN SMALL LETTER TURNED A
    u'\u0251': u'alpha', # LATIN SMALL LETTER ALPHA
    u'\u0252': u'alpha', # LATIN SMALL LETTER TURNED ALPHA
    u'\u0253': u'b', # LATIN SMALL LETTER B WITH HOOK
    u'\u0254': u'o', # LATIN SMALL LETTER OPEN O
    u'\u0255': u'c', # LATIN SMALL LETTER C WITH CURL
    u'\u0256': u'd', # LATIN SMALL LETTER D WITH TAIL
    u'\u0257': u'd', # LATIN SMALL LETTER D WITH HOOK
    u'\u025B': u'E', # LATIN SMALL LETTER OPEN E
    u'\u025F': u'j', # LATIN SMALL LETTER DOTLESS J WITH STROKE
    u'\u0260': u'g', # LATIN SMALL LETTER G WITH HOOK
    u'\u0261': u'g', # LATIN SMALL LETTER SCRIPT G
    u'\u0262': u'G', # LATIN LETTER SMALL CAPITAL G
    u'\u0263': u'gamma', # LATIN SMALL LETTER GAMMA
    u'\u0265': u'h', # LATIN SMALL LETTER TURNED H
    u'\u0266': u'h', # LATIN SMALL LETTER H WITH HOOK
    u'\u0268': u'i', # LATIN SMALL LETTER I WITH STROKE
    u'\u0269': u'iota', # LATIN SMALL LETTER IOTA
    u'\u026A': u'i', # LATIN LETTER SMALL CAPITAL I
    u'\u026B': u'l', # LATIN SMALL LETTER L WITH MIDDLE TILDE
    u'\u026C': u'l', # LATIN SMALL LETTER L WITH BELT
    u'\u026D': u'l', # LATIN SMALL LETTER L WITH RETROFLEX HOOK
    u'\u026F': u'm', # LATIN SMALL LETTER TURNED M
    u'\u0270': u'm', # LATIN SMALL LETTER TURNED M WITH LONG LEG
    u'\u0271': u'm', # LATIN SMALL LETTER M WITH HOOK
    u'\u0272': u'n', # LATIN SMALL LETTER N WITH LEFT HOOK
    u'\u0273': u'n', # LATIN SMALL LETTER N WITH RETROFLEX HOOK
    u'\u0274': u'N', # LATIN LETTER SMALL CAPITAL N
    u'\u0275': u'o', # LATIN SMALL LETTER BARRED O
    u'\u0276': u'OE', # LATIN LETTER SMALL CAPITAL OE
    u'\u0277': u'omega', # LATIN SMALL LETTER CLOSED OMEGA
    u'\u0278': u'phi', # LATIN SMALL LETTER PHI
    u'\u0279': u'r', # LATIN SMALL LETTER TURNED R
    u'\u027A': u'r', # LATIN SMALL LETTER TURNED R WITH LONG LEG
    u'\u027B': u'r', # LATIN SMALL LETTER TURNED R WITH HOOK
    u'\u027C': u'r', # LATIN SMALL LETTER R WITH LONG LEG
    u'\u027D': u'r', # LATIN SMALL LETTER R WITH TAIL
    u'\u027E': u'r', # LATIN SMALL LETTER R WITH FISHHOOK
    u'\u0280': u'R', # LATIN LETTER SMALL CAPITAL R
    u'\u0282': u's', # LATIN SMALL LETTER S WITH HOOK
    u'\u0284': u'j', # LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
    u'\u0287': u't', # LATIN SMALL LETTER TURNED T
    u'\u0288': u't', # LATIN SMALL LETTER T WITH RETROFLEX HOOK
    u'\u0289': u'u', # LATIN SMALL LETTER U BAR
    u'\u028A': u'upsilon', # LATIN SMALL LETTER UPSILON
    u'\u028B': u'v', # LATIN SMALL LETTER V WITH HOOK
    u'\u028C': u'v', # LATIN SMALL LETTER TURNED V
    u'\u028D': u'w', # LATIN SMALL LETTER TURNED W
    u'\u028E': u'y', # LATIN SMALL LETTER TURNED Y
    u'\u028F': u'Y', # LATIN LETTER SMALL CAPITAL Y
    u'\u0290': u'z', # LATIN SMALL LETTER Z WITH RETROFLEX HOOK
    u'\u0291': u'z', # LATIN SMALL LETTER Z WITH CURL
    u'\u0297': u'C', # LATIN LETTER STRETCHED C
    u'\u0299': u'B', # LATIN LETTER SMALL CAPITAL B
    u'\u029A': u'e', # LATIN SMALL LETTER CLOSED OPEN E
    u'\u029B': u'G', # LATIN LETTER SMALL CAPITAL G WITH HOOK
    u'\u029C': u'H', # LATIN LETTER SMALL CAPITAL H
    u'\u029D': u'j', # LATIN SMALL LETTER J WITH CROSSED-TAIL
    u'\u029E': u'k', # LATIN SMALL LETTER TURNED K
    u'\u029F': u'L', # LATIN LETTER SMALL CAPITAL L
    u'\u02A0': u'q', # LATIN SMALL LETTER Q WITH HOOK
    u'\u02A3': u'DZ', # LATIN SMALL LETTER DZ DIGRAPH
    u'\u02A5': u'dz', # LATIN SMALL LETTER DZ DIGRAPH WITH CURL
    u'\u02A6': u'ts', # LATIN SMALL LETTER TS DIGRAPH
    u'\u02A8': u'tc', # LATIN SMALL LETTER TC DIGRAPH WITH CURL
    u'\u02AA': u'ls', # LATIN SMALL LETTER LS DIGRAPH
    u'\u02AB': u'lz', # LATIN SMALL LETTER LZ DIGRAPH
    u'\u02AE': u'h', # LATIN SMALL LETTER TURNED H WITH FISHHOOK
    u'\u02AF': u'h', # LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL
    u'\u037E': u';', # GREEK QUESTION MARK
    u'\u0386': u'Alpha', # GREEK CAPITAL LETTER ALPHA WITH TONOS
    u'\u0388': u'Epsilon', # GREEK CAPITAL LETTER EPSILON WITH TONOS
    u'\u0389': u'Eta', # GREEK CAPITAL LETTER ETA WITH TONOS
    u'\u038A': u'Iota', # GREEK CAPITAL LETTER IOTA WITH TONOS
    u'\u038C': u'Omicron', # GREEK CAPITAL LETTER OMICRON WITH TONOS
    u'\u038E': u'Upsilon', # GREEK CAPITAL LETTER UPSILON WITH TONOS
    u'\u038F': u'Omega', # GREEK CAPITAL LETTER OMEGA WITH TONOS
    u'\u0390': u'iota', # GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
    u'\u0391': u'Alpha', # GREEK CAPITAL LETTER ALPHA
    u'\u0392': u'Beta', # GREEK CAPITAL LETTER BETA
    u'\u0393': u'Gamma', # GREEK CAPITAL LETTER GAMMA
    u'\u0394': u'Delta', # GREEK CAPITAL LETTER DELTA
    u'\u0395': u'Epsilon', # GREEK CAPITAL LETTER EPSILON
    u'\u0396': u'Zeta', # GREEK CAPITAL LETTER ZETA
    u'\u0397': u'Eta', # GREEK CAPITAL LETTER ETA
    u'\u0398': u'Theta', # GREEK CAPITAL LETTER THETA
    u'\u0399': u'Iota', # GREEK CAPITAL LETTER IOTA
    u'\u039A': u'Kappa', # GREEK CAPITAL LETTER KAPPA
    u'\u039B': u'Lamda', # GREEK CAPITAL LETTER LAMDA
    u'\u039C': u'Mu', # GREEK CAPITAL LETTER MU
    u'\u039D': u'Nu', # GREEK CAPITAL LETTER NU
    u'\u039E': u'Xi', # GREEK CAPITAL LETTER XI
    u'\u039F': u'Omicron', # GREEK CAPITAL LETTER OMICRON
    u'\u03A0': u'Pi', # GREEK CAPITAL LETTER PI
    u'\u03A1': u'Rho', # GREEK CAPITAL LETTER RHO
    u'\u03A3': u'Sigma', # GREEK CAPITAL LETTER SIGMA
    u'\u03A4': u'Tau', # GREEK CAPITAL LETTER TAU
    u'\u03A5': u'Upsilon', # GREEK CAPITAL LETTER UPSILON
    u'\u03A6': u'Phi', # GREEK CAPITAL LETTER PHI
    u'\u03A7': u'Chi', # GREEK CAPITAL LETTER CHI
    u'\u03A8': u'Psi', # GREEK CAPITAL LETTER PSI
    u'\u03A9': u'Omega', # GREEK CAPITAL LETTER OMEGA
    u'\u03AA': u'Iota', # GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
    u'\u03AB': u'Upsilon', # GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
    u'\u03AC': u'alpha', # GREEK SMALL LETTER ALPHA WITH TONOS
    u'\u03AD': u'epsilon', # GREEK SMALL LETTER EPSILON WITH TONOS
    u'\u03AE': u'eta', # GREEK SMALL LETTER ETA WITH TONOS
    u'\u03AF': u'iota', # GREEK SMALL LETTER IOTA WITH TONOS
    u'\u03B0': u'upsilon', # GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
    u'\u03B1': u'alpha', # GREEK SMALL LETTER ALPHA
    u'\u03B2': u'beta', # GREEK SMALL LETTER BETA
    u'\u03B3': u'gamma', # GREEK SMALL LETTER GAMMA
    u'\u03B4': u'delta', # GREEK SMALL LETTER DELTA
    u'\u03B5': u'epsilon', # GREEK SMALL LETTER EPSILON
    u'\u03B6': u'zeta', # GREEK SMALL LETTER ZETA
    u'\u03B7': u'eta', # GREEK SMALL LETTER ETA
    u'\u03B8': u'theta', # GREEK SMALL LETTER THETA
    u'\u03B9': u'iota', # GREEK SMALL LETTER IOTA
    u'\u03BA': u'kappa', # GREEK SMALL LETTER KAPPA
    u'\u03BB': u'lamda', # GREEK SMALL LETTER LAMDA
    u'\u03BC': u'mu', # GREEK SMALL LETTER MU
    u'\u03BD': u'nu', # GREEK SMALL LETTER NU
    u'\u03BE': u'xi', # GREEK SMALL LETTER XI
    u'\u03BF': u'omicron', # GREEK SMALL LETTER OMICRON
    u'\u03C0': u'pi', # GREEK SMALL LETTER PI
    u'\u03C1': u'rho', # GREEK SMALL LETTER RHO
    u'\u03C2': u'sigma', # GREEK SMALL LETTER FINAL SIGMA
    u'\u03C3': u'sigma', # GREEK SMALL LETTER SIGMA
    u'\u03C4': u'tau', # GREEK SMALL LETTER TAU
    u'\u03C5': u'upsilon', # GREEK SMALL LETTER UPSILON
    u'\u03C6': u'phi', # GREEK SMALL LETTER PHI
    u'\u03C7': u'chi', # GREEK SMALL LETTER CHI
    u'\u03C8': u'psi', # GREEK SMALL LETTER PSI
    u'\u03C9': u'omega', # GREEK SMALL LETTER OMEGA
    u'\u03CA': u'iota', # GREEK SMALL LETTER IOTA WITH DIALYTIKA
    u'\u03CB': u'upsilon', # GREEK SMALL LETTER UPSILON WITH DIALYTIKA
    u'\u03CC': u'omicron', # GREEK SMALL LETTER OMICRON WITH TONOS
    u'\u03CD': u'upsilon', # GREEK SMALL LETTER UPSILON WITH TONOS
    u'\u03CE': u'omega', # GREEK SMALL LETTER OMEGA WITH TONOS
    u'\u03D0': u'beta', # GREEK BETA SYMBOL
    u'\u03D1': u'theta', # GREEK THETA SYMBOL
    u'\u03D2': u'Upsilon', # GREEK UPSILON WITH HOOK SYMBOL
    u'\u03D3': u'Upsilon', # GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
    u'\u03D4': u'Upsilon', # GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL
    u'\u03D5': u'phi', # GREEK PHI SYMBOL
    u'\u03D6': u'pi', # GREEK PI SYMBOL
    u'\u03F0': u'kappa', # GREEK KAPPA SYMBOL
    u'\u03F1': u'rho', # GREEK RHO SYMBOL
    u'\u03F2': u'sigma', # GREEK LUNATE SIGMA SYMBOL
    u'\u03F4': u'Theta', # GREEK CAPITAL THETA SYMBOL
    u'\u03F5': u'epsilon', # GREEK LUNATE EPSILON SYMBOL
    u'\u03F9': u'Sigma', # GREEK CAPITAL LUNATE SIGMA SYMBOL
    u'\u03FC': u'Rho', # GREEK RHO WITH STROKE SYMBOL
    u'\u1E00': u'A', # LATIN CAPITAL LETTER A WITH RING BELOW
    u'\u1E01': u'a', # LATIN SMALL LETTER A WITH RING BELOW
    u'\u1E02': u'B', # LATIN CAPITAL LETTER B WITH DOT ABOVE
    u'\u1E03': u'b', # LATIN SMALL LETTER B WITH DOT ABOVE
    u'\u1E04': u'B', # LATIN CAPITAL LETTER B WITH DOT BELOW
    u'\u1E05': u'b', # LATIN SMALL LETTER B WITH DOT BELOW
    u'\u1E06': u'B', # LATIN CAPITAL LETTER B WITH LINE BELOW
    u'\u1E07': u'b', # LATIN SMALL LETTER B WITH LINE BELOW
    u'\u1E08': u'C', # LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
    u'\u1E09': u'c', # LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
    u'\u1E0A': u'D', # LATIN CAPITAL LETTER D WITH DOT ABOVE
    u'\u1E0B': u'd', # LATIN SMALL LETTER D WITH DOT ABOVE
    u'\u1E0C': u'D', # LATIN CAPITAL LETTER D WITH DOT BELOW
    u'\u1E0D': u'd', # LATIN SMALL LETTER D WITH DOT BELOW
    u'\u1E0E': u'D', # LATIN CAPITAL LETTER D WITH LINE BELOW
    u'\u1E0F': u'd', # LATIN SMALL LETTER D WITH LINE BELOW
    u'\u1E10': u'D', # LATIN CAPITAL LETTER D WITH CEDILLA
    u'\u1E11': u'd', # LATIN SMALL LETTER D WITH CEDILLA
    u'\u1E12': u'D', # LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
    u'\u1E13': u'd', # LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
    u'\u1E14': u'E', # LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
    u'\u1E15': u'e', # LATIN SMALL LETTER E WITH MACRON AND GRAVE
    u'\u1E16': u'E', # LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
    u'\u1E17': u'e', # LATIN SMALL LETTER E WITH MACRON AND ACUTE
    u'\u1E18': u'E', # LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
    u'\u1E19': u'e', # LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
    u'\u1E1A': u'E', # LATIN CAPITAL LETTER E WITH TILDE BELOW
    u'\u1E1B': u'e', # LATIN SMALL LETTER E WITH TILDE BELOW
    u'\u1E1C': u'E', # LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
    u'\u1E1D': u'e', # LATIN SMALL LETTER E WITH CEDILLA AND BREVE
    u'\u1E1E': u'F', # LATIN CAPITAL LETTER F WITH DOT ABOVE
    u'\u1E1F': u'f', # LATIN SMALL LETTER F WITH DOT ABOVE
    u'\u1E20': u'G', # LATIN CAPITAL LETTER G WITH MACRON
    u'\u1E21': u'g', # LATIN SMALL LETTER G WITH MACRON
    u'\u1E22': u'H', # LATIN CAPITAL LETTER H WITH DOT ABOVE
    u'\u1E23': u'h', # LATIN SMALL LETTER H WITH DOT ABOVE
    u'\u1E24': u'H', # LATIN CAPITAL LETTER H WITH DOT BELOW
    u'\u1E25': u'h', # LATIN SMALL LETTER H WITH DOT BELOW
    u'\u1E26': u'H', # LATIN CAPITAL LETTER H WITH DIAERESIS
    u'\u1E27': u'h', # LATIN SMALL LETTER H WITH DIAERESIS
    u'\u1E28': u'H', # LATIN CAPITAL LETTER H WITH CEDILLA
    u'\u1E29': u'h', # LATIN SMALL LETTER H WITH CEDILLA
    u'\u1E2A': u'H', # LATIN CAPITAL LETTER H WITH BREVE BELOW
    u'\u1E2B': u'h', # LATIN SMALL LETTER H WITH BREVE BELOW
    u'\u1E2C': u'I', # LATIN CAPITAL LETTER I WITH TILDE BELOW
    u'\u1E2D': u'i', # LATIN SMALL LETTER I WITH TILDE BELOW
    u'\u1E2E': u'I', # LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
    u'\u1E2F': u'i', # LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
    u'\u1E30': u'K', # LATIN CAPITAL LETTER K WITH ACUTE
    u'\u1E31': u'k', # LATIN SMALL LETTER K WITH ACUTE
    u'\u1E32': u'K', # LATIN CAPITAL LETTER K WITH DOT BELOW
    u'\u1E33': u'k', # LATIN SMALL LETTER K WITH DOT BELOW
    u'\u1E34': u'K', # LATIN CAPITAL LETTER K WITH LINE BELOW
    u'\u1E35': u'k', # LATIN SMALL LETTER K WITH LINE BELOW
    u'\u1E36': u'L', # LATIN CAPITAL LETTER L WITH DOT BELOW
    u'\u1E37': u'l', # LATIN SMALL LETTER L WITH DOT BELOW
    u'\u1E38': u'L', # LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
    u'\u1E39': u'l', # LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
    u'\u1E3A': u'L', # LATIN CAPITAL LETTER L WITH LINE BELOW
    u'\u1E3B': u'l', # LATIN SMALL LETTER L WITH LINE BELOW
    u'\u1E3C': u'L', # LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
    u'\u1E3D': u'l', # LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
    u'\u1E3E': u'M', # LATIN CAPITAL LETTER M WITH ACUTE
    u'\u1E3F': u'm', # LATIN SMALL LETTER M WITH ACUTE
    u'\u1E40': u'M', # LATIN CAPITAL LETTER M WITH DOT ABOVE
    u'\u1E41': u'm', # LATIN SMALL LETTER M WITH DOT ABOVE
    u'\u1E42': u'M', # LATIN CAPITAL LETTER M WITH DOT BELOW
    u'\u1E43': u'm', # LATIN SMALL LETTER M WITH DOT BELOW
    u'\u1E44': u'N', # LATIN CAPITAL LETTER N WITH DOT ABOVE
    u'\u1E45': u'n', # LATIN SMALL LETTER N WITH DOT ABOVE
    u'\u1E46': u'N', # LATIN CAPITAL LETTER N WITH DOT BELOW
    u'\u1E47': u'n', # LATIN SMALL LETTER N WITH DOT BELOW
    u'\u1E48': u'N', # LATIN CAPITAL LETTER N WITH LINE BELOW
    u'\u1E49': u'n', # LATIN SMALL LETTER N WITH LINE BELOW
    u'\u1E4A': u'N', # LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
    u'\u1E4B': u'n', # LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
    u'\u1E4C': u'O', # LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
    u'\u1E4D': u'o', # LATIN SMALL LETTER O WITH TILDE AND ACUTE
    u'\u1E4E': u'O', # LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
    u'\u1E4F': u'o', # LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
    u'\u1E50': u'O', # LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
    u'\u1E51': u'o', # LATIN SMALL LETTER O WITH MACRON AND GRAVE
    u'\u1E52': u'O', # LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
    u'\u1E53': u'o', # LATIN SMALL LETTER O WITH MACRON AND ACUTE
    u'\u1E54': u'P', # LATIN CAPITAL LETTER P WITH ACUTE
    u'\u1E55': u'p', # LATIN SMALL LETTER P WITH ACUTE
    u'\u1E56': u'P', # LATIN CAPITAL LETTER P WITH DOT ABOVE
    u'\u1E57': u'p', # LATIN SMALL LETTER P WITH DOT ABOVE
    u'\u1E58': u'R', # LATIN CAPITAL LETTER R WITH DOT ABOVE
    u'\u1E59': u'r', # LATIN SMALL LETTER R WITH DOT ABOVE
    u'\u1E5A': u'R', # LATIN CAPITAL LETTER R WITH DOT BELOW
    u'\u1E5B': u'r', # LATIN SMALL LETTER R WITH DOT BELOW
    u'\u1E5C': u'R', # LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
    u'\u1E5D': u'r', # LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
    u'\u1E5E': u'R', # LATIN CAPITAL LETTER R WITH LINE BELOW
    u'\u1E5F': u'r', # LATIN SMALL LETTER R WITH LINE BELOW
    u'\u1E60': u'S', # LATIN CAPITAL LETTER S WITH DOT ABOVE
    u'\u1E61': u's', # LATIN SMALL LETTER S WITH DOT ABOVE
    u'\u1E62': u'S', # LATIN CAPITAL LETTER S WITH DOT BELOW
    u'\u1E63': u's', # LATIN SMALL LETTER S WITH DOT BELOW
    u'\u1E64': u'S', # LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
    u'\u1E65': u's', # LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
    u'\u1E66': u'S', # LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
    u'\u1E67': u's', # LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
    u'\u1E68': u'S', # LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
    u'\u1E69': u's', # LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
    u'\u1E6A': u'T', # LATIN CAPITAL LETTER T WITH DOT ABOVE
    u'\u1E6B': u't', # LATIN SMALL LETTER T WITH DOT ABOVE
    u'\u1E6C': u'T', # LATIN CAPITAL LETTER T WITH DOT BELOW
    u'\u1E6D': u't', # LATIN SMALL LETTER T WITH DOT BELOW
    u'\u1E6E': u'T', # LATIN CAPITAL LETTER T WITH LINE BELOW
    u'\u1E6F': u't', # LATIN SMALL LETTER T WITH LINE BELOW
    u'\u1E70': u'T', # LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
    u'\u1E71': u't', # LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
    u'\u1E72': u'U', # LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
    u'\u1E73': u'u', # LATIN SMALL LETTER U WITH DIAERESIS BELOW
    u'\u1E74': u'U', # LATIN CAPITAL LETTER U WITH TILDE BELOW
    u'\u1E75': u'u', # LATIN SMALL LETTER U WITH TILDE BELOW
    u'\u1E76': u'U', # LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
    u'\u1E77': u'u', # LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
    u'\u1E78': u'U', # LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
    u'\u1E79': u'u', # LATIN SMALL LETTER U WITH TILDE AND ACUTE
    u'\u1E7A': u'U', # LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
    u'\u1E7B': u'u', # LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
    u'\u1E7C': u'V', # LATIN CAPITAL LETTER V WITH TILDE
    u'\u1E7D': u'v', # LATIN SMALL LETTER V WITH TILDE
    u'\u1E7E': u'V', # LATIN CAPITAL LETTER V WITH DOT BELOW
    u'\u1E7F': u'v', # LATIN SMALL LETTER V WITH DOT BELOW
    u'\u1E80': u'W', # LATIN CAPITAL LETTER W WITH GRAVE
    u'\u1E81': u'w', # LATIN SMALL LETTER W WITH GRAVE
    u'\u1E82': u'W', # LATIN CAPITAL LETTER W WITH ACUTE
    u'\u1E83': u'w', # LATIN SMALL LETTER W WITH ACUTE
    u'\u1E84': u'W', # LATIN CAPITAL LETTER W WITH DIAERESIS
    u'\u1E85': u'w', # LATIN SMALL LETTER W WITH DIAERESIS
    u'\u1E86': u'W', # LATIN CAPITAL LETTER W WITH DOT ABOVE
    u'\u1E87': u'w', # LATIN SMALL LETTER W WITH DOT ABOVE
    u'\u1E88': u'W', # LATIN CAPITAL LETTER W WITH DOT BELOW
    u'\u1E89': u'w', # LATIN SMALL LETTER W WITH DOT BELOW
    u'\u1E8A': u'X', # LATIN CAPITAL LETTER X WITH DOT ABOVE
    u'\u1E8B': u'x', # LATIN SMALL LETTER X WITH DOT ABOVE
    u'\u1E8C': u'X', # LATIN CAPITAL LETTER X WITH DIAERESIS
    u'\u1E8D': u'x', # LATIN SMALL LETTER X WITH DIAERESIS
    u'\u1E8E': u'Y', # LATIN CAPITAL LETTER Y WITH DOT ABOVE
    u'\u1E8F': u'y', # LATIN SMALL LETTER Y WITH DOT ABOVE
    u'\u1E90': u'Z', # LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
    u'\u1E91': u'z', # LATIN SMALL LETTER Z WITH CIRCUMFLEX
    u'\u1E92': u'Z', # LATIN CAPITAL LETTER Z WITH DOT BELOW
    u'\u1E93': u'z', # LATIN SMALL LETTER Z WITH DOT BELOW
    u'\u1E94': u'Z', # LATIN CAPITAL LETTER Z WITH LINE BELOW
    u'\u1E95': u'z', # LATIN SMALL LETTER Z WITH LINE BELOW
    u'\u1E96': u'h', # LATIN SMALL LETTER H WITH LINE BELOW
    u'\u1E97': u't', # LATIN SMALL LETTER T WITH DIAERESIS
    u'\u1E98': u'w', # LATIN SMALL LETTER W WITH RING ABOVE
    u'\u1E99': u'y', # LATIN SMALL LETTER Y WITH RING ABOVE
    u'\u1E9A': u'a', # LATIN SMALL LETTER A WITH RIGHT HALF RING
    u'\u1E9B': u's', # LATIN SMALL LETTER LONG S WITH DOT ABOVE
    u'\u1EA0': u'A', # LATIN CAPITAL LETTER A WITH DOT BELOW
    u'\u1EA1': u'a', # LATIN SMALL LETTER A WITH DOT BELOW
    u'\u1EA2': u'A', # LATIN CAPITAL LETTER A WITH HOOK ABOVE
    u'\u1EA3': u'a', # LATIN SMALL LETTER A WITH HOOK ABOVE
    u'\u1EA4': u'A', # LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
    u'\u1EA5': u'a', # LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
    u'\u1EA6': u'A', # LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
    u'\u1EA7': u'a', # LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
    u'\u1EA8': u'A', # LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
    u'\u1EA9': u'a', # LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
    u'\u1EAA': u'A', # LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
    u'\u1EAB': u'a', # LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
    u'\u1EAC': u'A', # LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    u'\u1EAD': u'a', # LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
    u'\u1EAE': u'A', # LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
    u'\u1EAF': u'a', # LATIN SMALL LETTER A WITH BREVE AND ACUTE
    u'\u1EB0': u'A', # LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
    u'\u1EB1': u'a', # LATIN SMALL LETTER A WITH BREVE AND GRAVE
    u'\u1EB2': u'A', # LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
    u'\u1EB3': u'a', # LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
    u'\u1EB4': u'A', # LATIN CAPITAL LETTER A WITH BREVE AND TILDE
    u'\u1EB5': u'a', # LATIN SMALL LETTER A WITH BREVE AND TILDE
    u'\u1EB6': u'A', # LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
    u'\u1EB7': u'a', # LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
    u'\u1EB8': u'E', # LATIN CAPITAL LETTER E WITH DOT BELOW
    u'\u1EB9': u'e', # LATIN SMALL LETTER E WITH DOT BELOW
    u'\u1EBA': u'E', # LATIN CAPITAL LETTER E WITH HOOK ABOVE
    u'\u1EBB': u'e', # LATIN SMALL LETTER E WITH HOOK ABOVE
    u'\u1EBC': u'E', # LATIN CAPITAL LETTER E WITH TILDE
    u'\u1EBD': u'e', # LATIN SMALL LETTER E WITH TILDE
    u'\u1EBE': u'E', # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
    u'\u1EBF': u'e', # LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
    u'\u1EC0': u'E', # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
    u'\u1EC1': u'e', # LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
    u'\u1EC2': u'E', # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
    u'\u1EC3': u'e', # LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
    u'\u1EC4': u'E', # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
    u'\u1EC5': u'e', # LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
    u'\u1EC6': u'E', # LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    u'\u1EC7': u'e', # LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
    u'\u1EC8': u'I', # LATIN CAPITAL LETTER I WITH HOOK ABOVE
    u'\u1EC9': u'i', # LATIN SMALL LETTER I WITH HOOK ABOVE
    u'\u1ECA': u'I', # LATIN CAPITAL LETTER I WITH DOT BELOW
    u'\u1ECB': u'i', # LATIN SMALL LETTER I WITH DOT BELOW
    u'\u1ECC': u'O', # LATIN CAPITAL LETTER O WITH DOT BELOW
    u'\u1ECD': u'o', # LATIN SMALL LETTER O WITH DOT BELOW
    u'\u1ECE': u'O', # LATIN CAPITAL LETTER O WITH HOOK ABOVE
    u'\u1ECF': u'o', # LATIN SMALL LETTER O WITH HOOK ABOVE
    u'\u1ED0': u'O', # LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
    u'\u1ED1': u'o', # LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
    u'\u1ED2': u'O', # LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
    u'\u1ED3': u'o', # LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
    u'\u1ED4': u'O', # LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
    u'\u1ED5': u'o', # LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
    u'\u1ED6': u'O', # LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
    u'\u1ED7': u'o', # LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
    u'\u1ED8': u'O', # LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    u'\u1ED9': u'o', # LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
    u'\u1EDA': u'O', # LATIN CAPITAL LETTER O WITH HORN AND ACUTE
    u'\u1EDB': u'o', # LATIN SMALL LETTER O WITH HORN AND ACUTE
    u'\u1EDC': u'O', # LATIN CAPITAL LETTER O WITH HORN AND GRAVE
    u'\u1EDD': u'o', # LATIN SMALL LETTER O WITH HORN AND GRAVE
    u'\u1EDE': u'O', # LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
    u'\u1EDF': u'o', # LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
    u'\u1EE0': u'O', # LATIN CAPITAL LETTER O WITH HORN AND TILDE
    u'\u1EE1': u'o', # LATIN SMALL LETTER O WITH HORN AND TILDE
    u'\u1EE2': u'O', # LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
    u'\u1EE3': u'o', # LATIN SMALL LETTER O WITH HORN AND DOT BELOW
    u'\u1EE4': u'U', # LATIN CAPITAL LETTER U WITH DOT BELOW
    u'\u1EE5': u'u', # LATIN SMALL LETTER U WITH DOT BELOW
    u'\u1EE6': u'U', # LATIN CAPITAL LETTER U WITH HOOK ABOVE
    u'\u1EE7': u'u', # LATIN SMALL LETTER U WITH HOOK ABOVE
    u'\u1EE8': u'U', # LATIN CAPITAL LETTER U WITH HORN AND ACUTE
    u'\u1EE9': u'u', # LATIN SMALL LETTER U WITH HORN AND ACUTE
    u'\u1EEA': u'U', # LATIN CAPITAL LETTER U WITH HORN AND GRAVE
    u'\u1EEB': u'u', # LATIN SMALL LETTER U WITH HORN AND GRAVE
    u'\u1EEC': u'U', # LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
    u'\u1EED': u'u', # LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
    u'\u1EEE': u'U', # LATIN CAPITAL LETTER U WITH HORN AND TILDE
    u'\u1EEF': u'u', # LATIN SMALL LETTER U WITH HORN AND TILDE
    u'\u1EF0': u'U', # LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
    u'\u1EF1': u'u', # LATIN SMALL LETTER U WITH HORN AND DOT BELOW
    u'\u1EF2': u'Y', # LATIN CAPITAL LETTER Y WITH GRAVE
    u'\u1EF3': u'y', # LATIN SMALL LETTER Y WITH GRAVE
    u'\u1EF4': u'Y', # LATIN CAPITAL LETTER Y WITH DOT BELOW
    u'\u1EF5': u'y', # LATIN SMALL LETTER Y WITH DOT BELOW
    u'\u1EF6': u'Y', # LATIN CAPITAL LETTER Y WITH HOOK ABOVE
    u'\u1EF7': u'y', # LATIN SMALL LETTER Y WITH HOOK ABOVE
    u'\u1EF8': u'Y', # LATIN CAPITAL LETTER Y WITH TILDE
    u'\u1EF9': u'y', # LATIN SMALL LETTER Y WITH TILDE
    u'\u2010': u'-', # HYPHEN
    u'\u2011': u'-', # NON-BREAKING HYPHEN
    u'\u2012': u'-', # FIGURE DASH
    u'\u2013': u'-', # EN DASH
    u'\u2014': u'-', # EM DASH
    u'\u2015': u'--', # HORIZONTAL BAR
    u'\u2016': u'', # DOUBLE VERTICAL LINE
    u'\u2017': u'_', # DOUBLE LOW LINE
    u'\u2018': u"'", # LEFT SINGLE QUOTATION MARK
    u'\u2019': u"'", # RIGHT SINGLE QUOTATION MARK
    u'\u201A': u',', # SINGLE LOW-9 QUOTATION MARK
    u'\u201B': u"'", # SINGLE HIGH-REVERSED-9 QUOTATION MARK
    u'\u201C': u'"', # LEFT DOUBLE QUOTATION MARK
    u'\u201D': u'"', # RIGHT DOUBLE QUOTATION MARK
    u'\u201E': u'"', # DOUBLE LOW-9 QUOTATION MARK
    u'\u201F': u'"', # DOUBLE HIGH-REVERSED-9 QUOTATION MARK
    u'\u2024': u'.', # ONE DOT LEADER
    u'\u2025': u'..', # TWO DOT LEADER
    u'\u2026': u'...', # HORIZONTAL ELLIPSIS
    u'\u202F': u' ', # NARROW NO-BREAK SPACE
    u'\u2030': u'0/00', # PER MILLE SIGN
    u'\u2031': u'0/000', # PER TEN THOUSAND SIGN
    u'\u2032': u"'", # PRIME
    u'\u2033': u'"', # DOUBLE PRIME
    u'\u2034': u"'''", # TRIPLE PRIME
    u'\u2035': u'`', # REVERSED PRIME
    u'\u2036': u'"', # REVERSED DOUBLE PRIME
    u'\u2037': u"'''", # REVERSED TRIPLE PRIME
    u'\u2038': u'^', # CARET
    u'\u2039': u'<', # SINGLE LEFT-POINTING ANGLE QUOTATION MARK
    u'\u203A': u'>', # SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
    u'\u203C': u'!!', # DOUBLE EXCLAMATION MARK
    u'\u203D': u'?', # INTERROBANG
    u'\u2044': u'/', # FRACTION SLASH
    u'\u2045': u'[', # LEFT SQUARE BRACKET WITH QUILL
    u'\u2046': u']', # RIGHT SQUARE BRACKET WITH QUILL
    u'\u2047': u'??', # DOUBLE QUESTION MARK
    u'\u2048': u'?!', # QUESTION EXCLAMATION MARK
    u'\u2049': u'!?', # EXCLAMATION QUESTION MARK
    u'\u204E': u'*', # LOW ASTERISK
    u'\u2052': u'%', # COMMERCIAL MINUS SIGN
    u'\u2053': u'~', # SWUNG DASH
    u'\u2056': u'...', # THREE DOT PUNCTUATION
    u'\u2057': u"''''", # QUADRUPLE PRIME
    u'\u2058': u'....', # FOUR DOT PUNCTUATION
    u'\u2059': u'.....', # FIVE DOT PUNCTUATION
    u'\u205A': u'..', # TWO DOT PUNCTUATION
    u'\u205F': u' ', # MEDIUM MATHEMATICAL SPACE
    u'\u2100': u'a/c', # ACCOUNT OF
    u'\u2101': u'a/s', # ADDRESSED TO THE SUBJECT
    u'\u2102': u'C', # DOUBLE-STRUCK CAPITAL C
    u'\u2103': u'C', # DEGREE CELSIUS
    u'\u2105': u'c/o', # CARE OF
    u'\u2106': u'c/u', # CADA UNA
    u'\u2107': u'E', # EULER CONSTANT
    u'\u2109': u'F', # DEGREE FAHRENHEIT
    u'\u210A': u'g', # SCRIPT SMALL G
    u'\u210B': u'H', # SCRIPT CAPITAL H
    u'\u210C': u'H', # BLACK-LETTER CAPITAL H
    u'\u210D': u'H', # DOUBLE-STRUCK CAPITAL H
    u'\u210E': u'h', # PLANCK CONSTANT
    u'\u210F': u'h', # PLANCK CONSTANT OVER TWO PI
    u'\u2110': u'I', # SCRIPT CAPITAL I
    u'\u2111': u'I', # BLACK-LETTER CAPITAL I
    u'\u2112': u'L', # SCRIPT CAPITAL L
    u'\u2113': u'l', # SCRIPT SMALL L
    u'\u2115': u'N', # DOUBLE-STRUCK CAPITAL N
    u'\u2116': u'No', # NUMERO SIGN
    u'\u2117': u'(p)', # SOUND RECORDING COPYRIGHT
    u'\u2118': u'P', # SCRIPT CAPITAL P
    u'\u2119': u'P', # DOUBLE-STRUCK CAPITAL P
    u'\u211A': u'Q', # DOUBLE-STRUCK CAPITAL Q
    u'\u211B': u'R', # SCRIPT CAPITAL R
    u'\u211C': u'R', # BLACK-LETTER CAPITAL R
    u'\u211D': u'R', # DOUBLE-STRUCK CAPITAL R
    u'\u211E': u'Px', # PRESCRIPTION TAKE
    u'\u2120': u'SM', # SERVICE MARK
    u'\u2121': u'TEL', # TELEPHONE SIGN
    u'\u2122': u'TM', # TRADE MARK SIGN
    u'\u2124': u'Z', # DOUBLE-STRUCK CAPITAL Z
    u'\u2126': u'Omega', # OHM SIGN
    u'\u2128': u'Z', # BLACK-LETTER CAPITAL Z
    u'\u2129': u'iota', # TURNED GREEK SMALL LETTER IOTA
    u'\u212A': u'K', # KELVIN SIGN
    u'\u212B': u'A', # ANGSTROM SIGN
    u'\u212C': u'B', # SCRIPT CAPITAL B
    u'\u212D': u'C', # BLACK-LETTER CAPITAL C
    u'\u212E': u'e', # ESTIMATED SYMBOL
    u'\u212F': u'e', # SCRIPT SMALL E
    u'\u2130': u'E', # SCRIPT CAPITAL E
    u'\u2131': u'F', # SCRIPT CAPITAL F
    u'\u2132': u'F', # TURNED CAPITAL F
    u'\u2133': u'M', # SCRIPT CAPITAL M
    u'\u2134': u'o', # SCRIPT SMALL O
    u'\u2139': u'i', # INFORMATION SOURCE
    u'\u213A': u'Q', # ROTATED CAPITAL Q
    u'\u213B': u'FAX', # FACSIMILE SIGN
    u'\u213C': u'pi', # DOUBLE-STRUCK SMALL PI
    u'\u213D': u'gamma', # DOUBLE-STRUCK SMALL GAMMA
    u'\u213E': u'Gamma', # DOUBLE-STRUCK CAPITAL GAMMA
    u'\u213F': u'PI', # DOUBLE-STRUCK CAPITAL PI
    u'\u2141': u'G', # TURNED SANS-SERIF CAPITAL G
    u'\u2142': u'L', # TURNED SANS-SERIF CAPITAL L
    u'\u2144': u'Y', # TURNED SANS-SERIF CAPITAL Y
    u'\u2145': u'D', # DOUBLE-STRUCK ITALIC CAPITAL D
    u'\u2146': u'd', # DOUBLE-STRUCK ITALIC SMALL D
    u'\u2147': u'e', # DOUBLE-STRUCK ITALIC SMALL E
    u'\u2148': u'i', # DOUBLE-STRUCK ITALIC SMALL I
    u'\u2149': u'j', # DOUBLE-STRUCK ITALIC SMALL J
    u'\u214B': u'&', # TURNED AMPERSAND
    u'\u2153': u'1/3', # VULGAR FRACTION ONE THIRD
    u'\u2154': u'2/3', # VULGAR FRACTION TWO THIRDS
    u'\u2155': u'1/5', # VULGAR FRACTION ONE FIFTH
    u'\u2156': u'2/5', # VULGAR FRACTION TWO FIFTHS
    u'\u2157': u'3/5', # VULGAR FRACTION THREE FIFTHS
    u'\u2158': u'4/5', # VULGAR FRACTION FOUR FIFTHS
    u'\u2159': u'1/6', # VULGAR FRACTION ONE SIXTH
    u'\u215A': u'5/6', # VULGAR FRACTION FIVE SIXTHS
    u'\u215B': u'1/8', # VULGAR FRACTION ONE EIGHTH
    u'\u215C': u'3/8', # VULGAR FRACTION THREE EIGHTHS
    u'\u215D': u'5/8', # VULGAR FRACTION FIVE EIGHTHS
    u'\u215E': u'7/8', # VULGAR FRACTION SEVEN EIGHTHS
    u'\u215F': u'1/', # FRACTION NUMERATOR ONE
    u'\u2160': u'I', # ROMAN NUMERAL ONE
    u'\u2161': u'II', # ROMAN NUMERAL TWO
    u'\u2162': u'III', # ROMAN NUMERAL THREE
    u'\u2163': u'IV', # ROMAN NUMERAL FOUR
    u'\u2164': u'V', # ROMAN NUMERAL FIVE
    u'\u2165': u'VI', # ROMAN NUMERAL SIX
    u'\u2166': u'VII', # ROMAN NUMERAL SEVEN
    u'\u2167': u'VIII', # ROMAN NUMERAL EIGHT
    u'\u2168': u'IX', # ROMAN NUMERAL NINE
    u'\u2169': u'X', # ROMAN NUMERAL TEN
    u'\u216A': u'XI', # ROMAN NUMERAL ELEVEN
    u'\u216B': u'XII', # ROMAN NUMERAL TWELVE
    u'\u216C': u'L', # ROMAN NUMERAL FIFTY
    u'\u216D': u'C', # ROMAN NUMERAL ONE HUNDRED
    u'\u216E': u'D', # ROMAN NUMERAL FIVE HUNDRED
    u'\u216F': u'M', # ROMAN NUMERAL ONE THOUSAND
    u'\u2170': u'i', # SMALL ROMAN NUMERAL ONE
    u'\u2171': u'ii', # SMALL ROMAN NUMERAL TWO
    u'\u2172': u'iii', # SMALL ROMAN NUMERAL THREE
    u'\u2173': u'iv', # SMALL ROMAN NUMERAL FOUR
    u'\u2174': u'v', # SMALL ROMAN NUMERAL FIVE
    u'\u2175': u'vi', # SMALL ROMAN NUMERAL SIX
    u'\u2176': u'vii', # SMALL ROMAN NUMERAL SEVEN
    u'\u2177': u'viii', # SMALL ROMAN NUMERAL EIGHT
    u'\u2178': u'ix', # SMALL ROMAN NUMERAL NINE
    u'\u2179': u'x', # SMALL ROMAN NUMERAL TEN
    u'\u217A': u'xi', # SMALL ROMAN NUMERAL ELEVEN
    u'\u217B': u'xii', # SMALL ROMAN NUMERAL TWELVE
    u'\u217C': u'l', # SMALL ROMAN NUMERAL FIFTY
    u'\u217D': u'c', # SMALL ROMAN NUMERAL ONE HUNDRED
    u'\u217E': u'd', # SMALL ROMAN NUMERAL FIVE HUNDRED
    u'\u217F': u'm', # SMALL ROMAN NUMERAL ONE THOUSAND
    u'\u2180': u'CD', # ROMAN NUMERAL ONE THOUSAND C D
    u'\u2190': u'<-', # LEFTWARDS ARROW
    u'\u2192': u'->', # RIGHTWARDS ARROW
    u'\u2194': u'<->', # LEFT RIGHT ARROW
    u'\u219A': u'<-', # LEFTWARDS ARROW WITH STROKE
    u'\u219B': u'->', # RIGHTWARDS ARROW WITH STROKE
    u'\u21AE': u'<->', # LEFT RIGHT ARROW WITH STROKE
    u'\u21CD': u'<=', # LEFTWARDS DOUBLE ARROW WITH STROKE
    u'\u21CE': u'<=>', # LEFT RIGHT DOUBLE ARROW WITH STROKE
    u'\u21CF': u'=>', # RIGHTWARDS DOUBLE ARROW WITH STROKE
    u'\u21D0': u'<=', # LEFTWARDS DOUBLE ARROW
    u'\u21D2': u'=>', # RIGHTWARDS DOUBLE ARROW
    u'\u21D4': u'<=>', # LEFT RIGHT DOUBLE ARROW
    u'\u2303': u'^', # UP ARROWHEAD
    u'\u2329': u'<', # LEFT-POINTING ANGLE BRACKET
    u'\u232A': u'>', # RIGHT-POINTING ANGLE BRACKET
    u'\u239B': u'(', # LEFT PARENTHESIS UPPER HOOK
    u'\u239C': u'(', # LEFT PARENTHESIS EXTENSION
    u'\u239D': u'(', # LEFT PARENTHESIS LOWER HOOK
    u'\u239E': u')', # RIGHT PARENTHESIS UPPER HOOK
    u'\u239F': u')', # RIGHT PARENTHESIS EXTENSION
    u'\u23A0': u')', # RIGHT PARENTHESIS LOWER HOOK
    u'\u23A1': u'[', # LEFT SQUARE BRACKET UPPER CORNER
    u'\u23A2': u'[', # LEFT SQUARE BRACKET EXTENSION
    u'\u23A3': u'[', # LEFT SQUARE BRACKET LOWER CORNER
    u'\u23A4': u']', # RIGHT SQUARE BRACKET UPPER CORNER
    u'\u23A5': u']', # RIGHT SQUARE BRACKET EXTENSION
    u'\u23A6': u']', # RIGHT SQUARE BRACKET LOWER CORNER
    u'\u23A7': u'{', # LEFT CURLY BRACKET UPPER HOOK
    u'\u23A8': u'{', # LEFT CURLY BRACKET MIDDLE PIECE
    u'\u23A9': u'{', # LEFT CURLY BRACKET LOWER HOOK
    u'\u23AB': u'}', # RIGHT CURLY BRACKET UPPER HOOK
    u'\u23AC': u'}', # RIGHT CURLY BRACKET MIDDLE PIECE
    u'\u23AD': u'}', # RIGHT CURLY BRACKET LOWER HOOK
    u'\u2460': u'1', # CIRCLED DIGIT ONE
    u'\u2461': u'2', # CIRCLED DIGIT TWO
    u'\u2462': u'3', # CIRCLED DIGIT THREE
    u'\u2463': u'4', # CIRCLED DIGIT FOUR
    u'\u2464': u'5', # CIRCLED DIGIT FIVE
    u'\u2465': u'6', # CIRCLED DIGIT SIX
    u'\u2466': u'7', # CIRCLED DIGIT SEVEN
    u'\u2467': u'8', # CIRCLED DIGIT EIGHT
    u'\u2468': u'9', # CIRCLED DIGIT NINE
    u'\u2469': u'10', # CIRCLED NUMBER TEN
    u'\u246A': u'11', # CIRCLED NUMBER ELEVEN
    u'\u246B': u'12', # CIRCLED NUMBER TWELVE
    u'\u246C': u'13', # CIRCLED NUMBER THIRTEEN
    u'\u246D': u'14', # CIRCLED NUMBER FOURTEEN
    u'\u246E': u'15', # CIRCLED NUMBER FIFTEEN
    u'\u246F': u'16', # CIRCLED NUMBER SIXTEEN
    u'\u2470': u'17', # CIRCLED NUMBER SEVENTEEN
    u'\u2471': u'18', # CIRCLED NUMBER EIGHTEEN
    u'\u2472': u'19', # CIRCLED NUMBER NINETEEN
    u'\u2473': u'20', # CIRCLED NUMBER TWENTY
    u'\u2474': u'(1)', # PARENTHESIZED DIGIT ONE
    u'\u2475': u'(2)', # PARENTHESIZED DIGIT TWO
    u'\u2476': u'(3)', # PARENTHESIZED DIGIT THREE
    u'\u2477': u'(4)', # PARENTHESIZED DIGIT FOUR
    u'\u2478': u'(5)', # PARENTHESIZED DIGIT FIVE
    u'\u2479': u'(6)', # PARENTHESIZED DIGIT SIX
    u'\u247A': u'(7)', # PARENTHESIZED DIGIT SEVEN
    u'\u247B': u'(8)', # PARENTHESIZED DIGIT EIGHT
    u'\u247C': u'(9)', # PARENTHESIZED DIGIT NINE
    u'\u247D': u'(10)', # PARENTHESIZED NUMBER TEN
    u'\u247E': u'(11)', # PARENTHESIZED NUMBER ELEVEN
    u'\u247F': u'(12)', # PARENTHESIZED NUMBER TWELVE
    u'\u2480': u'(13)', # PARENTHESIZED NUMBER THIRTEEN
    u'\u2481': u'(14)', # PARENTHESIZED NUMBER FOURTEEN
    u'\u2482': u'(15)', # PARENTHESIZED NUMBER FIFTEEN
    u'\u2483': u'(16)', # PARENTHESIZED NUMBER SIXTEEN
    u'\u2484': u'(17)', # PARENTHESIZED NUMBER SEVENTEEN
    u'\u2485': u'(18)', # PARENTHESIZED NUMBER EIGHTEEN
    u'\u2486': u'(19)', # PARENTHESIZED NUMBER NINETEEN
    u'\u2487': u'(20)', # PARENTHESIZED NUMBER TWENTY
    u'\u2488': u'1.', # DIGIT ONE FULL STOP
    u'\u2489': u'2.', # DIGIT TWO FULL STOP
    u'\u248A': u'3.', # DIGIT THREE FULL STOP
    u'\u248B': u'4.', # DIGIT FOUR FULL STOP
    u'\u248C': u'5.', # DIGIT FIVE FULL STOP
    u'\u248D': u'6.', # DIGIT SIX FULL STOP
    u'\u248E': u'7.', # DIGIT SEVEN FULL STOP
    u'\u248F': u'8.', # DIGIT EIGHT FULL STOP
    u'\u2490': u'9.', # DIGIT NINE FULL STOP
    u'\u2491': u'10.', # NUMBER TEN FULL STOP
    u'\u2492': u'11.', # NUMBER ELEVEN FULL STOP
    u'\u2493': u'12.', # NUMBER TWELVE FULL STOP
    u'\u2494': u'13.', # NUMBER THIRTEEN FULL STOP
    u'\u2495': u'14.', # NUMBER FOURTEEN FULL STOP
    u'\u2496': u'15.', # NUMBER FIFTEEN FULL STOP
    u'\u2497': u'16.', # NUMBER SIXTEEN FULL STOP
    u'\u2498': u'17.', # NUMBER SEVENTEEN FULL STOP
    u'\u2499': u'18.', # NUMBER EIGHTEEN FULL STOP
    u'\u249A': u'19.', # NUMBER NINETEEN FULL STOP
    u'\u249B': u'20.', # NUMBER TWENTY FULL STOP
    u'\u249C': u'(a)', # PARENTHESIZED LATIN SMALL LETTER A
    u'\u249D': u'(b)', # PARENTHESIZED LATIN SMALL LETTER B
    u'\u249E': u'(c)', # PARENTHESIZED LATIN SMALL LETTER C
    u'\u249F': u'(d)', # PARENTHESIZED LATIN SMALL LETTER D
    u'\u24A0': u'(e)', # PARENTHESIZED LATIN SMALL LETTER E
    u'\u24A1': u'(f)', # PARENTHESIZED LATIN SMALL LETTER F
    u'\u24A2': u'(g)', # PARENTHESIZED LATIN SMALL LETTER G
    u'\u24A3': u'(h)', # PARENTHESIZED LATIN SMALL LETTER H
    u'\u24A4': u'(i)', # PARENTHESIZED LATIN SMALL LETTER I
    u'\u24A5': u'(j)', # PARENTHESIZED LATIN SMALL LETTER J
    u'\u24A6': u'(k)', # PARENTHESIZED LATIN SMALL LETTER K
    u'\u24A7': u'(l)', # PARENTHESIZED LATIN SMALL LETTER L
    u'\u24A8': u'(m)', # PARENTHESIZED LATIN SMALL LETTER M
    u'\u24A9': u'(n)', # PARENTHESIZED LATIN SMALL LETTER N
    u'\u24AA': u'(o)', # PARENTHESIZED LATIN SMALL LETTER O
    u'\u24AB': u'(p)', # PARENTHESIZED LATIN SMALL LETTER P
    u'\u24AC': u'(q)', # PARENTHESIZED LATIN SMALL LETTER Q
    u'\u24AD': u'(r)', # PARENTHESIZED LATIN SMALL LETTER R
    u'\u24AE': u'(s)', # PARENTHESIZED LATIN SMALL LETTER S
    u'\u24AF': u'(t)', # PARENTHESIZED LATIN SMALL LETTER T
    u'\u24B0': u'(u)', # PARENTHESIZED LATIN SMALL LETTER U
    u'\u24B1': u'(v)', # PARENTHESIZED LATIN SMALL LETTER V
    u'\u24B2': u'(w)', # PARENTHESIZED LATIN SMALL LETTER W
    u'\u24B3': u'(x)', # PARENTHESIZED LATIN SMALL LETTER X
    u'\u24B4': u'(y)', # PARENTHESIZED LATIN SMALL LETTER Y
    u'\u24B5': u'(z)', # PARENTHESIZED LATIN SMALL LETTER Z
    u'\u24B6': u'A', # CIRCLED LATIN CAPITAL LETTER A
    u'\u24B7': u'B', # CIRCLED LATIN CAPITAL LETTER B
    u'\u24B8': u'C', # CIRCLED LATIN CAPITAL LETTER C
    u'\u24B9': u'D', # CIRCLED LATIN CAPITAL LETTER D
    u'\u24BA': u'E', # CIRCLED LATIN CAPITAL LETTER E
    u'\u24BB': u'F', # CIRCLED LATIN CAPITAL LETTER F
    u'\u24BC': u'G', # CIRCLED LATIN CAPITAL LETTER G
    u'\u24BD': u'H', # CIRCLED LATIN CAPITAL LETTER H
    u'\u24BE': u'I', # CIRCLED LATIN CAPITAL LETTER I
    u'\u24BF': u'J', # CIRCLED LATIN CAPITAL LETTER J
    u'\u24C0': u'K', # CIRCLED LATIN CAPITAL LETTER K
    u'\u24C1': u'L', # CIRCLED LATIN CAPITAL LETTER L
    u'\u24C2': u'M', # CIRCLED LATIN CAPITAL LETTER M
    u'\u24C3': u'N', # CIRCLED LATIN CAPITAL LETTER N
    u'\u24C4': u'O', # CIRCLED LATIN CAPITAL LETTER O
    u'\u24C5': u'P', # CIRCLED LATIN CAPITAL LETTER P
    u'\u24C6': u'Q', # CIRCLED LATIN CAPITAL LETTER Q
    u'\u24C7': u'R', # CIRCLED LATIN CAPITAL LETTER R
    u'\u24C8': u'S', # CIRCLED LATIN CAPITAL LETTER S
    u'\u24C9': u'T', # CIRCLED LATIN CAPITAL LETTER T
    u'\u24CA': u'U', # CIRCLED LATIN CAPITAL LETTER U
    u'\u24CB': u'V', # CIRCLED LATIN CAPITAL LETTER V
    u'\u24CC': u'W', # CIRCLED LATIN CAPITAL LETTER W
    u'\u24CD': u'X', # CIRCLED LATIN CAPITAL LETTER X
    u'\u24CE': u'Y', # CIRCLED LATIN CAPITAL LETTER Y
    u'\u24CF': u'Z', # CIRCLED LATIN CAPITAL LETTER Z
    u'\u24D0': u'a', # CIRCLED LATIN SMALL LETTER A
    u'\u24D1': u'b', # CIRCLED LATIN SMALL LETTER B
    u'\u24D2': u'c', # CIRCLED LATIN SMALL LETTER C
    u'\u24D3': u'd', # CIRCLED LATIN SMALL LETTER D
    u'\u24D4': u'e', # CIRCLED LATIN SMALL LETTER E
    u'\u24D5': u'f', # CIRCLED LATIN SMALL LETTER F
    u'\u24D6': u'g', # CIRCLED LATIN SMALL LETTER G
    u'\u24D7': u'h', # CIRCLED LATIN SMALL LETTER H
    u'\u24D8': u'i', # CIRCLED LATIN SMALL LETTER I
    u'\u24D9': u'j', # CIRCLED LATIN SMALL LETTER J
    u'\u24DA': u'k', # CIRCLED LATIN SMALL LETTER K
    u'\u24DB': u'l', # CIRCLED LATIN SMALL LETTER L
    u'\u24DC': u'm', # CIRCLED LATIN SMALL LETTER M
    u'\u24DD': u'n', # CIRCLED LATIN SMALL LETTER N
    u'\u24DE': u'o', # CIRCLED LATIN SMALL LETTER O
    u'\u24DF': u'p', # CIRCLED LATIN SMALL LETTER P
    u'\u24E0': u'q', # CIRCLED LATIN SMALL LETTER Q
    u'\u24E1': u'r', # CIRCLED LATIN SMALL LETTER R
    u'\u24E2': u's', # CIRCLED LATIN SMALL LETTER S
    u'\u24E3': u't', # CIRCLED LATIN SMALL LETTER T
    u'\u24E4': u'u', # CIRCLED LATIN SMALL LETTER U
    u'\u24E5': u'v', # CIRCLED LATIN SMALL LETTER V
    u'\u24E6': u'w', # CIRCLED LATIN SMALL LETTER W
    u'\u24E7': u'x', # CIRCLED LATIN SMALL LETTER X
    u'\u24E8': u'y', # CIRCLED LATIN SMALL LETTER Y
    u'\u24E9': u'z', # CIRCLED LATIN SMALL LETTER Z
    u'\u24EA': u'0', # CIRCLED DIGIT ZERO
    u'\u24EB': u'(11)', # NEGATIVE CIRCLED NUMBER ELEVEN
    u'\u24EC': u'(12)', # NEGATIVE CIRCLED NUMBER TWELVE
    u'\u24ED': u'(13)', # NEGATIVE CIRCLED NUMBER THIRTEEN
    u'\u24EE': u'(14)', # NEGATIVE CIRCLED NUMBER FOURTEEN
    u'\u24EF': u'(15)', # NEGATIVE CIRCLED NUMBER FIFTEEN
    u'\u24F0': u'(16)', # NEGATIVE CIRCLED NUMBER SIXTEEN
    u'\u24F1': u'(17)', # NEGATIVE CIRCLED NUMBER SEVENTEEN
    u'\u24F2': u'(18)', # NEGATIVE CIRCLED NUMBER EIGHTEEN
    u'\u24F3': u'(19)', # NEGATIVE CIRCLED NUMBER NINETEEN
    u'\u24F4': u'(20)', # NEGATIVE CIRCLED NUMBER TWENTY
    u'\u24F5': u'(1)', # DOUBLE CIRCLED DIGIT ONE
    u'\u24F6': u'(2)', # DOUBLE CIRCLED DIGIT TWO
    u'\u24F7': u'(3)', # DOUBLE CIRCLED DIGIT THREE
    u'\u24F8': u'(4)', # DOUBLE CIRCLED DIGIT FOUR
    u'\u24F9': u'(5)', # DOUBLE CIRCLED DIGIT FIVE
    u'\u24FA': u'(6)', # DOUBLE CIRCLED DIGIT SIX
    u'\u24FB': u'(7)', # DOUBLE CIRCLED DIGIT SEVEN
    u'\u24FC': u'(8)', # DOUBLE CIRCLED DIGIT EIGHT
    u'\u24FD': u'(9)', # DOUBLE CIRCLED DIGIT NINE
    u'\u24FE': u'(10)', # DOUBLE CIRCLED NUMBER TEN
    u'\u24FF': u'(0)', # NEGATIVE CIRCLED DIGIT ZERO
    u'\u3000': u' ', # IDEOGRAPHIC SPACE
    u'\u3001': u',', # IDEOGRAPHIC COMMA
    u'\u3003': u'"', # DITTO MARK
    u'\u3007': u'0', # IDEOGRAPHIC NUMBER ZERO
    u'\u3008': u'<', # LEFT ANGLE BRACKET
    u'\u3009': u'>', # RIGHT ANGLE BRACKET
    u'\u300A': u'<<', # LEFT DOUBLE ANGLE BRACKET
    u'\u300B': u'>>', # RIGHT DOUBLE ANGLE BRACKET
    u'\u301B': u']', # RIGHT WHITE SQUARE BRACKET
    u'\u301C': u'~', # WAVE DASH
    u'\u301D': u'"', # REVERSED DOUBLE PRIME QUOTATION MARK
    u'\u301E': u'"', # DOUBLE PRIME QUOTATION MARK
    u'\u3021': u'1', # HANGZHOU NUMERAL ONE
    u'\u3022': u'2', # HANGZHOU NUMERAL TWO
    u'\u3023': u'3', # HANGZHOU NUMERAL THREE
    u'\u3024': u'4', # HANGZHOU NUMERAL FOUR
    u'\u3025': u'5', # HANGZHOU NUMERAL FIVE
    u'\u3026': u'6', # HANGZHOU NUMERAL SIX
    u'\u3027': u'7', # HANGZHOU NUMERAL SEVEN
    u'\u3028': u'8', # HANGZHOU NUMERAL EIGHT
    u'\u3029': u'9', # HANGZHOU NUMERAL NINE
    u'\uFB00': u'ff', # LATIN SMALL LIGATURE FF
    u'\uFB01': u'fi', # LATIN SMALL LIGATURE FI
    u'\uFB02': u'fl', # LATIN SMALL LIGATURE FL
    u'\uFB03': u'ffi', # LATIN SMALL LIGATURE FFI
    u'\uFB04': u'ffl', # LATIN SMALL LIGATURE FFL
    u'\uFB05': u'st', # LATIN SMALL LIGATURE LONG S T
    u'\uFB06': u'st', # LATIN SMALL LIGATURE ST
    u'\uFB29': u'+', # HEBREW LETTER ALTERNATIVE PLUS SIGN
    u'\uFE50': u',', # SMALL COMMA
    u'\uFE51': u',', # SMALL IDEOGRAPHIC COMMA
    u'\uFE52': u'.', # SMALL FULL STOP
    u'\uFE54': u';', # SMALL SEMICOLON
    u'\uFE55': u':', # SMALL COLON
    u'\uFE56': u'?', # SMALL QUESTION MARK
    u'\uFE57': u'!', # SMALL EXCLAMATION MARK
    u'\uFE58': u'-', # SMALL EM DASH
    u'\uFE59': u'(', # SMALL LEFT PARENTHESIS
    u'\uFE5A': u')', # SMALL RIGHT PARENTHESIS
    u'\uFE5B': u'{', # SMALL LEFT CURLY BRACKET
    u'\uFE5C': u'}', # SMALL RIGHT CURLY BRACKET
    u'\uFE5D': u'(', # SMALL LEFT TORTOISE SHELL BRACKET
    u'\uFE5E': u')', # SMALL RIGHT TORTOISE SHELL BRACKET
    u'\uFE5F': u'#', # SMALL NUMBER SIGN
    u'\uFE60': u'&', # SMALL AMPERSAND
    u'\uFE61': u'*', # SMALL ASTERISK
    u'\uFE62': u'+', # SMALL PLUS SIGN
    u'\uFE63': u'-', # SMALL HYPHEN-MINUS
    u'\uFE64': u'<', # SMALL LESS-THAN SIGN
    u'\uFE65': u'>', # SMALL GREATER-THAN SIGN
    u'\uFE66': u'=', # SMALL EQUALS SIGN
    u'\uFE67': u'![null]!', # null
    u'\uFE68': u'\\', # SMALL REVERSE SOLIDUS
    u'\uFE69': u'$', # SMALL DOLLAR SIGN
    u'\uFE6A': u'%', # SMALL PERCENT SIGN
    u'\uFE6B': u'@', # SMALL COMMERCIAL AT
    u'\uFF00': u'![null]!', # null
    u'\uFF01': u'!', # FULLWIDTH EXCLAMATION MARK
    u'\uFF02': u'"', # FULLWIDTH QUOTATION MARK
    u'\uFF03': u'#', # FULLWIDTH NUMBER SIGN
    u'\uFF04': u'$', # FULLWIDTH DOLLAR SIGN
    u'\uFF05': u'%', # FULLWIDTH PERCENT SIGN
    u'\uFF06': u'&', # FULLWIDTH AMPERSAND
    u'\uFF07': u"'", # FULLWIDTH APOSTROPHE
    u'\uFF08': u'(', # FULLWIDTH LEFT PARENTHESIS
    u'\uFF09': u')', # FULLWIDTH RIGHT PARENTHESIS
    u'\uFF0A': u'*', # FULLWIDTH ASTERISK
    u'\uFF0B': u'+', # FULLWIDTH PLUS SIGN
    u'\uFF0C': u',', # FULLWIDTH COMMA
    u'\uFF0D': u'-', # FULLWIDTH HYPHEN-MINUS
    u'\uFF0E': u'.', # FULLWIDTH FULL STOP
    u'\uFF0F': u'/', # FULLWIDTH SOLIDUS
    u'\uFF10': u'0', # FULLWIDTH DIGIT ZERO
    u'\uFF11': u'1', # FULLWIDTH DIGIT ONE
    u'\uFF12': u'2', # FULLWIDTH DIGIT TWO
    u'\uFF13': u'3', # FULLWIDTH DIGIT THREE
    u'\uFF14': u'4', # FULLWIDTH DIGIT FOUR
    u'\uFF15': u'5', # FULLWIDTH DIGIT FIVE
    u'\uFF16': u'6', # FULLWIDTH DIGIT SIX
    u'\uFF17': u'7', # FULLWIDTH DIGIT SEVEN
    u'\uFF18': u'8', # FULLWIDTH DIGIT EIGHT
    u'\uFF19': u'9', # FULLWIDTH DIGIT NINE
    u'\uFF1A': u':', # FULLWIDTH COLON
    u'\uFF1B': u';', # FULLWIDTH SEMICOLON
    u'\uFF1C': u'<', # FULLWIDTH LESS-THAN SIGN
    u'\uFF1D': u'=', # FULLWIDTH EQUALS SIGN
    u'\uFF1E': u'>', # FULLWIDTH GREATER-THAN SIGN
    u'\uFF1F': u'?', # FULLWIDTH QUESTION MARK
    u'\uFF20': u'@', # FULLWIDTH COMMERCIAL AT
    u'\uFF21': u'A', # FULLWIDTH LATIN CAPITAL LETTER A
    u'\uFF22': u'B', # FULLWIDTH LATIN CAPITAL LETTER B
    u'\uFF23': u'C', # FULLWIDTH LATIN CAPITAL LETTER C
    u'\uFF24': u'D', # FULLWIDTH LATIN CAPITAL LETTER D
    u'\uFF25': u'E', # FULLWIDTH LATIN CAPITAL LETTER E
    u'\uFF26': u'F', # FULLWIDTH LATIN CAPITAL LETTER F
    u'\uFF27': u'G', # FULLWIDTH LATIN CAPITAL LETTER G
    u'\uFF28': u'H', # FULLWIDTH LATIN CAPITAL LETTER H
    u'\uFF29': u'I', # FULLWIDTH LATIN CAPITAL LETTER I
    u'\uFF2A': u'J', # FULLWIDTH LATIN CAPITAL LETTER J
    u'\uFF2B': u'K', # FULLWIDTH LATIN CAPITAL LETTER K
    u'\uFF2C': u'L', # FULLWIDTH LATIN CAPITAL LETTER L
    u'\uFF2D': u'M', # FULLWIDTH LATIN CAPITAL LETTER M
    u'\uFF2E': u'N', # FULLWIDTH LATIN CAPITAL LETTER N
    u'\uFF2F': u'O', # FULLWIDTH LATIN CAPITAL LETTER O
    u'\uFF30': u'P', # FULLWIDTH LATIN CAPITAL LETTER P
    u'\uFF31': u'Q', # FULLWIDTH LATIN CAPITAL LETTER Q
    u'\uFF32': u'R', # FULLWIDTH LATIN CAPITAL LETTER R
    u'\uFF33': u'S', # FULLWIDTH LATIN CAPITAL LETTER S
    u'\uFF34': u'T', # FULLWIDTH LATIN CAPITAL LETTER T
    u'\uFF35': u'U', # FULLWIDTH LATIN CAPITAL LETTER U
    u'\uFF36': u'V', # FULLWIDTH LATIN CAPITAL LETTER V
    u'\uFF37': u'W', # FULLWIDTH LATIN CAPITAL LETTER W
    u'\uFF38': u'X', # FULLWIDTH LATIN CAPITAL LETTER X
    u'\uFF39': u'Y', # FULLWIDTH LATIN CAPITAL LETTER Y
    u'\uFF3A': u'Z', # FULLWIDTH LATIN CAPITAL LETTER Z
    u'\uFF3B': u'[', # FULLWIDTH LEFT SQUARE BRACKET
    u'\uFF3C': u'\\', # FULLWIDTH REVERSE SOLIDUS
    u'\uFF3D': u']', # FULLWIDTH RIGHT SQUARE BRACKET
    u'\uFF3E': u'^', # FULLWIDTH CIRCUMFLEX ACCENT
    u'\uFF3F': u'_', # FULLWIDTH LOW LINE
    u'\uFF40': u'`', # FULLWIDTH GRAVE ACCENT
    u'\uFF41': u'a', # FULLWIDTH LATIN SMALL LETTER A
    u'\uFF42': u'b', # FULLWIDTH LATIN SMALL LETTER B
    u'\uFF43': u'c', # FULLWIDTH LATIN SMALL LETTER C
    u'\uFF44': u'd', # FULLWIDTH LATIN SMALL LETTER D
    u'\uFF45': u'e', # FULLWIDTH LATIN SMALL LETTER E
    u'\uFF46': u'f', # FULLWIDTH LATIN SMALL LETTER F
    u'\uFF47': u'g', # FULLWIDTH LATIN SMALL LETTER G
    u'\uFF48': u'h', # FULLWIDTH LATIN SMALL LETTER H
    u'\uFF49': u'i', # FULLWIDTH LATIN SMALL LETTER I
    u'\uFF4A': u'j', # FULLWIDTH LATIN SMALL LETTER J
    u'\uFF4B': u'k', # FULLWIDTH LATIN SMALL LETTER K
    u'\uFF4C': u'l', # FULLWIDTH LATIN SMALL LETTER L
    u'\uFF4D': u'm', # FULLWIDTH LATIN SMALL LETTER M
    u'\uFF4E': u'n', # FULLWIDTH LATIN SMALL LETTER N
    u'\uFF4F': u'o', # FULLWIDTH LATIN SMALL LETTER O
    u'\uFF50': u'p', # FULLWIDTH LATIN SMALL LETTER P
    u'\uFF51': u'q', # FULLWIDTH LATIN SMALL LETTER Q
    u'\uFF52': u'r', # FULLWIDTH LATIN SMALL LETTER R
    u'\uFF53': u's', # FULLWIDTH LATIN SMALL LETTER S
    u'\uFF54': u't', # FULLWIDTH LATIN SMALL LETTER T
    u'\uFF55': u'u', # FULLWIDTH LATIN SMALL LETTER U
    u'\uFF56': u'v', # FULLWIDTH LATIN SMALL LETTER V
    u'\uFF57': u'w', # FULLWIDTH LATIN SMALL LETTER W
    u'\uFF58': u'x', # FULLWIDTH LATIN SMALL LETTER X
    u'\uFF59': u'y', # FULLWIDTH LATIN SMALL LETTER Y
    u'\uFF5A': u'z', # FULLWIDTH LATIN SMALL LETTER Z
    u'\uFF5B': u'{', # FULLWIDTH LEFT CURLY BRACKET
    u'\uFF5C': u'', # FULLWIDTH VERTICAL LINE
    u'\uFF5D': u'}', # FULLWIDTH RIGHT CURLY BRACKET
    u'\uFF5E': u'~', # FULLWIDTH TILDE
    u'\uFF5F': u'(', # FULLWIDTH LEFT WHITE PARENTHESIS
    u'\uFF60': u')', # FULLWIDTH RIGHT WHITE PARENTHESIS
    u'\uFF64': u',', # HALFWIDTH IDEOGRAPHIC COMMA
    u'\uFFE9': u'<-', # HALFWIDTH LEFTWARDS ARROW
    u'\uFFEB': u'->', # HALFWIDTH RIGHTWARDS ARROW
}
